import type { BridgeItem, BridgeSearchParams, PaginationResponse, BridgeDetail } from '@/types/bridge'

// Mock桥梁数据 — 使用线上系统真实地名
const mockBridges: BridgeItem[] = [
  // ---- 人行天桥（5条，确保第1页可见） ----
  {
    key: '17',
    region: '杭州市西湖区',
    name: '天目山路人行天桥',
    type: '人行天桥',
    cityClassification: '—',
    structureType: '钢结构人行天桥',
    buildTime: '2020-06-15',
    isNavigationBridge: false,
    hasMonitorDevice: false,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-18',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '杭州市交通运输局',
    industryPerson: '张明',
    industryContact: '0571-88000001',
    facilityManageUnit: '杭州市市政设施管理中心',
    facilityManagePerson: '李强',
    facilityManageContact: '0571-88000002',
    facilityMaintainUnit: '杭州市桥梁养护公司',
    facilityMaintainPerson: '王勇',
    facilityMaintainContact: '0571-88000003',
    policeUnit: '杭州市交警支队',
    policeContact: '赵刚',
    policeContactPhone: '0571-88000004',
    bridgeLocation: '杭州市西湖区天目山路与教工路交叉口',
    isLargeTransportChannel: '否',
    overpassCard: {
      name: '天目山路人行天桥', roadName: '天目山路', district: '杭州市西湖区', cardNo: 'OPDQ-2020-001',
      manageUnit: '杭州市市政设施管理中心', buildUnit: '杭州市政工程建设集团', designUnit: '浙江省交通规划设计研究院',
      supervisorUnit: '浙江工程监理咨询公司', constructionUnit: '杭州城建工程公司', buildDate: '2020-06',
      structureType: '钢结构简支梁', designLoad: '人群荷载 4.0kN/m²', seismicIntensity: '6度（0.05g）',
      bridgeLength: '52.0', passageWidth: '4.5', carriagewayWidth: '—', sidewalkWidth: '3.0', designClearHeight: '5.0',
      superstructure: '钢箱梁', substructure: '钢管混凝土桥墩', deckDecorationArea: '234',
      sidewalkPavement: '环氧防滑涂层', expansionJointType: '模数式伸缩缝', settlementJointCount: '2',
      railingStructure: '不锈钢复合栏杆', railingTotalLength: '104', bearingCount: '4',
      roadTransverseSlope: '1.0%', drainageFacility: '纵向排水沟+雨水口',
      lightingName: 'LED桥面灯', lightingCount: '24', powerName: '配电箱', powerCount: '2',
      fireFightingName: '干粉灭火器', fireFightingCount: '8',
      escalatorBrand: '上海三菱', escalatorCount: '2', elevatorBrand: '通力电梯', elevatorCount: '2',
      audit: '陈明', review: '张工', draft: '王工', cardDate: '2020-06-30',
    },
  },
  {
    key: '18',
    region: '杭州市拱墅区',
    name: '莫干山路人行天桥',
    type: '人行天桥',
    cityClassification: '—',
    structureType: '钢结构人行天桥',
    buildTime: '2019-05-20',
    isNavigationBridge: false,
    hasMonitorDevice: false,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-05-12',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '杭州市交通运输局',
    industryPerson: '张明',
    industryContact: '0571-88000001',
    facilityManageUnit: '杭州市市政设施管理中心',
    facilityManagePerson: '李强',
    facilityManageContact: '0571-88000002',
    facilityMaintainUnit: '杭州市桥梁养护公司',
    facilityMaintainPerson: '王勇',
    facilityMaintainContact: '0571-88000003',
    policeUnit: '杭州市交警支队',
    policeContact: '赵刚',
    policeContactPhone: '0571-88000004',
    bridgeLocation: '杭州市拱墅区莫干山路与文一路交叉口',
    isLargeTransportChannel: '否',
    overpassCard: {
      name: '莫干山路人行天桥', roadName: '莫干山路', district: '杭州市拱墅区', cardNo: 'OPDQ-2019-002',
      manageUnit: '杭州市市政设施管理中心', buildUnit: '杭州市政工程建设集团', designUnit: '浙江省交通规划设计研究院',
      supervisorUnit: '浙江工程监理咨询公司', constructionUnit: '杭州城建工程公司', buildDate: '2019-05',
      structureType: '钢结构简支梁', designLoad: '人群荷载 4.0kN/m²', seismicIntensity: '6度（0.05g）',
      bridgeLength: '48.0', passageWidth: '4.0', carriagewayWidth: '—', sidewalkWidth: '2.8', designClearHeight: '5.0',
      superstructure: '钢箱梁', substructure: '钢管混凝土桥墩', deckDecorationArea: '192',
      sidewalkPavement: '环氧防滑涂层', expansionJointType: '模数式伸缩缝', settlementJointCount: '2',
      railingStructure: '不锈钢复合栏杆', railingTotalLength: '96', bearingCount: '4',
      roadTransverseSlope: '1.0%', drainageFacility: '纵向排水沟+雨水口',
      lightingName: 'LED桥面灯', lightingCount: '20', powerName: '配电箱', powerCount: '2',
      fireFightingName: '干粉灭火器', fireFightingCount: '6',
      escalatorBrand: '上海三菱', escalatorCount: '2', elevatorBrand: '通力电梯', elevatorCount: '2',
      audit: '陈明', review: '张工', draft: '王工', cardDate: '2019-05-30',
    },
  },
  {
    key: '19',
    region: '宁波市海曙区',
    name: '中山路人行天桥',
    type: '人行天桥',
    cityClassification: '—',
    structureType: '钢结构人行天桥',
    buildTime: '2018-09-10',
    isNavigationBridge: false,
    hasMonitorDevice: false,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-04-20',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '宁波市交通运输局',
    industryPerson: '刘伟',
    industryContact: '0574-87000001',
    facilityManageUnit: '宁波市市政设施管理中心',
    facilityManagePerson: '陈刚',
    facilityManageContact: '0574-87000002',
    facilityMaintainUnit: '宁波市桥梁养护公司',
    facilityMaintainPerson: '赵明',
    facilityMaintainContact: '0574-87000003',
    policeUnit: '宁波市交警支队',
    policeContact: '孙强',
    policeContactPhone: '0574-87000004',
    bridgeLocation: '宁波市海曙区中山东路与解放路交叉口',
    isLargeTransportChannel: '否',
    overpassCard: {
      name: '中山路人行天桥', roadName: '中山东路', district: '宁波市海曙区', cardNo: 'OPDQ-2018-003',
      manageUnit: '宁波市市政设施管理中心', buildUnit: '宁波市政工程建设集团', designUnit: '浙江省交通规划设计研究院',
      supervisorUnit: '浙江工程监理咨询公司', constructionUnit: '宁波城建工程公司', buildDate: '2018-09',
      structureType: '钢结构连续梁', designLoad: '人群荷载 4.0kN/m²', seismicIntensity: '6度（0.05g）',
      bridgeLength: '55.0', passageWidth: '5.0', carriagewayWidth: '—', sidewalkWidth: '3.2', designClearHeight: '5.2',
      superstructure: '钢箱梁', substructure: '钢管混凝土桥墩', deckDecorationArea: '275',
      sidewalkPavement: '环氧防滑涂层', expansionJointType: '模数式伸缩缝', settlementJointCount: '3',
      railingStructure: '不锈钢复合栏杆', railingTotalLength: '110', bearingCount: '6',
      roadTransverseSlope: '1.0%', drainageFacility: '纵向排水沟+雨水口',
      lightingName: 'LED桥面灯', lightingCount: '28', powerName: '配电箱', powerCount: '3',
      fireFightingName: '干粉灭火器', fireFightingCount: '8',
      escalatorBrand: '日立电梯', escalatorCount: '2', elevatorBrand: '奥的斯电梯', elevatorCount: '2',
      audit: '李明', review: '王工', draft: '陈工', cardDate: '2018-09-30',
    },
  },
  {
    key: '20',
    region: '温州市鹿城区',
    name: '车站大道人行天桥',
    type: '人行天桥',
    cityClassification: '—',
    structureType: '钢结构人行天桥',
    buildTime: '2021-03-15',
    isNavigationBridge: false,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-06-08',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '温州市交通运输局',
    industryPerson: '周杰',
    industryContact: '0577-89000001',
    facilityManageUnit: '温州市市政设施管理中心',
    facilityManagePerson: '吴亮',
    facilityManageContact: '0577-89000002',
    facilityMaintainUnit: '温州市桥梁养护公司',
    facilityMaintainPerson: '郑明',
    facilityMaintainContact: '0577-89000003',
    policeUnit: '温州市交警支队',
    policeContact: '黄强',
    policeContactPhone: '0577-89000004',
    bridgeLocation: '温州市鹿城区车站大道与锦绣路交叉口',
    isLargeTransportChannel: '否',
    overpassCard: {
      name: '车站大道人行天桥', roadName: '车站大道', district: '温州市鹿城区', cardNo: 'OPDQ-2021-004',
      manageUnit: '温州市市政设施管理中心', buildUnit: '温州市政工程建设集团', designUnit: '浙江省交通规划设计研究院',
      supervisorUnit: '浙江工程监理咨询公司', constructionUnit: '温州城建工程公司', buildDate: '2021-03',
      structureType: '钢结构简支梁', designLoad: '人群荷载 4.0kN/m²', seismicIntensity: '6度（0.05g）',
      bridgeLength: '42.0', passageWidth: '3.8', carriagewayWidth: '—', sidewalkWidth: '2.5', designClearHeight: '4.8',
      superstructure: '钢箱梁', substructure: '钢管混凝土桥墩', deckDecorationArea: '160',
      sidewalkPavement: '环氧防滑涂层', expansionJointType: '模数式伸缩缝', settlementJointCount: '2',
      railingStructure: '不锈钢复合栏杆', railingTotalLength: '84', bearingCount: '4',
      roadTransverseSlope: '1.0%', drainageFacility: '纵向排水沟+雨水口',
      lightingName: 'LED桥面灯', lightingCount: '16', powerName: '配电箱', powerCount: '2',
      fireFightingName: '干粉灭火器', fireFightingCount: '4',
      escalatorBrand: '上海三菱', escalatorCount: '2', elevatorBrand: '通力电梯', elevatorCount: '2',
      audit: '周明', review: '陈工', draft: '李工', cardDate: '2021-03-30',
    },
  },
  {
    key: '21',
    region: '嘉兴市南湖区',
    name: '中环南路人行天桥',
    type: '人行天桥',
    cityClassification: '—',
    structureType: '钢结构人行天桥',
    buildTime: '2022-07-01',
    isNavigationBridge: false,
    hasMonitorDevice: false,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-05',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '嘉兴市交通运输局',
    industryPerson: '徐明',
    industryContact: '0573-82000001',
    facilityManageUnit: '嘉兴市市政设施管理中心',
    facilityManagePerson: '杨刚',
    facilityManageContact: '0573-82000002',
    facilityMaintainUnit: '嘉兴市桥梁养护公司',
    facilityMaintainPerson: '韩亮',
    facilityMaintainContact: '0573-82000003',
    policeUnit: '嘉兴市交警支队',
    policeContact: '林强',
    policeContactPhone: '0573-82000004',
    bridgeLocation: '嘉兴市南湖区中环南路与新气象路交叉口',
    isLargeTransportChannel: '否',
    overpassCard: {
      name: '中环南路人行天桥', roadName: '中环南路', district: '嘉兴市南湖区', cardNo: 'OPDQ-2022-005',
      manageUnit: '嘉兴市市政设施管理中心', buildUnit: '嘉兴市政工程建设集团', designUnit: '浙江省交通规划设计研究院',
      supervisorUnit: '浙江工程监理咨询公司', constructionUnit: '嘉兴城建工程公司', buildDate: '2022-07',
      structureType: '钢结构简支梁', designLoad: '人群荷载 4.0kN/m²', seismicIntensity: '6度（0.05g）',
      bridgeLength: '38.0', passageWidth: '3.5', carriagewayWidth: '—', sidewalkWidth: '2.5', designClearHeight: '4.5',
      superstructure: '钢箱梁', substructure: '钢管混凝土桥墩', deckDecorationArea: '133',
      sidewalkPavement: '环氧防滑涂层', expansionJointType: '模数式伸缩缝', settlementJointCount: '2',
      railingStructure: '不锈钢复合栏杆', railingTotalLength: '76', bearingCount: '4',
      roadTransverseSlope: '1.0%', drainageFacility: '纵向排水沟+雨水口',
      lightingName: 'LED桥面灯', lightingCount: '14', powerName: '配电箱', powerCount: '2',
      fireFightingName: '干粉灭火器', fireFightingCount: '4',
      escalatorBrand: '上海三菱', escalatorCount: '2', elevatorBrand: '通力电梯', elevatorCount: '2',
      audit: '徐明', review: '杨工', draft: '韩工', cardDate: '2022-07-30',
    },
  },
  // ---- 原有数据 ----
  {
    key: '1',
    region: '杭州市市辖区',
    name: '测试-复兴大桥',
    type: '城市道路桥梁',
    cityClassification: '大桥',
    structureType: '测试-复兴大桥梁式桥;子桥1悬索桥;子桥2刚架桥',
    buildTime: '2008-12-01',
    span: 1376,
    isNavigationBridge: false,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-06-22',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '浙江省-省政府机构-省建设厅-杭州市政工程局',
    industryPerson: '王雨晴',
    industryContact: '17360312375',
    facilityManageUnit: '浙江省-省政府机构-省建设厅-杭州市政工程局',
    facilityManagePerson: '王雨晴',
    facilityManageContact: '17360312375',
    facilityMaintainUnit: '杭州市政养护公司',
    facilityMaintainPerson: '张琦峰',
    facilityMaintainContact: '15268470922',
    policeUnit: '杭州市公安局交警支队',
    policeContact: '李俊琦',
    policeContactPhone: '13567194276',
    // 公安交警联动单位（对齐线上：3条记录）
    policeRecords: [
      { unit: '杭州市公安局交警支队', contact: '李俊琦', phone: '13567194276' },
      { unit: '杭州市公安局交警支队', contact: '任浩', phone: '13616559871' },
      { unit: '杭州市公安局交警支队', contact: '袁正品', phone: '13958129229' },
    ],
    bridgeLocation: 'MULTILINESTRING((120.1738 30.2181,120.1821 30.2254,120.1897 30.2318))',
    isLargeTransportChannel: '否',
    // 通航资料卡（对齐线上）
    navigationCard: {
      unit: '测试',
      bridgeName: '测试-复兴大桥',
      bridgeNo: 'FXDQ-001',
      bridgeFunctionType: '城市桥梁',
      isNonRestrictedBridge: '否',
      province: '浙江省',
      city: '杭州市',
      county: '市辖区',
      fourVerticalTwoHorizontalWaterway: '钱塘江干线航道',
      coastalSeaArea: '—',
      waterway: '钱塘江',
      coastalCrossingWaterway: '—',
      representativeShipType: '内河货船',
      inlandWaterwayCurrentGrade: 'Ⅲ级',
      inlandWaterwayPlanGrade: 'Ⅲ级',
      dailyShipFlow: '日均 120 艘',
      navigationHoleSpanAndLayout: '主跨通航，单孔双向',
      bridgeWaterwayMaintenanceScale: '220m×18m',
      bridgeWaterAreaScope: '主通航孔上下游各 500m',
      mainNavigationHoleMode: '单向/双向',
      mainNavigationClearHeight: '18m',
      mainNavigationClearWidth: '120m',
      designHighestNavigationWaterLevel: '7.5m',
      pierAntiCollisionCapacity: '满足 1000t 级船舶撞击',
      navigationHolePierAntiCollisionFacility: '设有防撞护舷',
      activeWarningSystem: '否',
      bridgeNavigationAidMark: '是',
      bridgeAreaWaterwayBuoy: '是',
      buildUnit: '杭州市政工程建设集团',
      operationManageUnit: '杭州市政工程局',
      operationManageContact: '0571-88886666',
      maritimeAuthority: '浙江省港航管理中心',
      waterwayMaintainUnit: '杭州市港航养护中心',
      antiCollisionPlan: '是',
      emergencyPlanInLocal: '是',
      fourTypeBridgeFunctionType: '公路桥',
      coastal: '否',
      inland: '是',
      bridgeType: '特大桥',
      remark: '',
    },
    // 桥梁资料卡（对齐线上）
    bridgeCard: {
      unit: '测试单位',
      // 一般资料
      cardName: '测试-复兴大桥',
      roadName: '中河高架路',
      crossLevel: '跨越钱塘江（跨江）',
      cardLocation: '杭州市钱塘江中段',
      manageUnit: '浙江省-省政府机构-省建设厅-城市建设处',
      maintainUnit: '越城区公用事业集团',
      buildUnit: '浙江桥梁工程建设集团',
      designUnit: '浙江省交通规划设计研究院',
      supervisorUnit: '浙江桥梁工程监理公司',
      constructionUnit: '浙江大桥建设工程有限公司',
      buildDate: '2008-12',
      totalCost: '12.5亿元',
      maintainGrade: 'Ⅰ类养护',
      maintainLevel: '特等养护',
      roadGrade: '城市快速路',
      structureType: '梁式桥',
      designLoad: '公路-I级',
      limitLoad: '限载55t',
      seismicIntensity: '6度',
      skewAngle: '0°',
      bridgeSpans: '6跨',
      spanCombination: '90+120+180+120+90+776',
      deckArea: '39800㎡',
      bridgeTotalLength: '1376m',
      bridgeTotalWidth: '28.5m',
      carriagewayWidth: '24m',
      sidewalkWidth: '2×2m',
      riverGrade: 'Ⅲ级航道',
      highestWaterLevel: '9.5m',
      normalWaterLevel: '5.2m',
      // 上部结构
      girderForm: '预应力混凝土箱梁',
      girderSize: '单箱多室',
      girderCount: '6片',
      crossBeamForm: '钢筋混凝土横梁',
      mainSpanClearance: '18m',
      bridgeClearHeight: '24m',
      archRiseSpanRatio: '1/5',
      bearingType: '球型钢支座',
      bearingCount: '24个',
      deckStructure: '现浇混凝土铺装层',
      deckPavementThickness: '10cm',
      expansionJointType: '模数式伸缩缝',
      expansionJointCount: '10道',
      mainBridgeLongitudinalSlope: '1.5%',
      mainBridgeTransverseSlope: '2%',
      approachBridgeLongitudinalSlope: '1.2%',
      approachBridgeTransverseSlope: '1.5%',
      // 下部结构 - 桥墩
      pierForm: '钢筋混凝土桥墩',
      pierCount: '10个',
      pierElevation: '12.5m',
      capBeamSize: '200×200cm',
      pierBaseElevation: '-3.2m',
      pierBaseplateSize: '350×250cm',
      pierPileSize: 'φ1500mm钻孔灌注桩',
      pierPileCount: '40根',
      // 下部结构 - 桥台
      abutmentForm: '重力式桥台',
      abutmentCount: '2个',
      abutmentElevation: '10.2m',
      abutmentBaseElevation: '-2.5m',
      capSize: '120×100cm',
      abutmentBaseplateSize: '200×150cm',
      abutmentPileSize: 'φ1200mm钻孔灌注桩',
      abutmentPileCount: '12根',
      retainingPlateThickness: '35cm',
      wingWallForm: '八字翼墙',
      wingWallLength: '8m',
      // 附属工程
      collectorSize: '50×30cm',
      collectorCount: '36个',
      drainPipeSize: 'φ100mm',
      drainPipeLength: '1200m',
      railingTotalLength: '2752m',
      railingStructure: '不锈钢护栏',
      endColumnSize: '30×30cm',
      bankProtectionType: '浆砌片石护坡',
      approachRetainingWallType: '重力式挡土墙',
      attachedPipe: {
        waterPipe: '有',
        gasPipe: '有',
        powerCable: '有',
        telecomCable: '有',
      },
      // 桥梁概况
      overview: '测试-复兴大桥跨越钱塘江，为城市快速路桥梁，主桥采用预应力混凝土箱梁结构。',
      // 制表信息
      audit: '张明',
      review: '李华',
      draft: '王芳',
      cardDate: '2026-06-22',
    },
    // 子桥资料卡
    subBridges: [
      {
        name: '子桥1', structureType: '悬索桥', maintainGrade: 'Ⅰ类养护', span: '680m', length: '1280m', width: '28.5m', buildDate: '2008-12',
        card: {
          unitName: '测试站桥',
          cardName: '子桥1',
          roadName: '中环高架路',
          crossLevel: '跨越钱塘江（跨省一级）',
          cardLocation: '杭州市钱塘江中区域',
          manageUnit: '浙江省市政工程局',
          maintainUnit: '越城区公用事业集团',
          buildUnit: '浙江桥梁工程建设集团',
          designUnit: '浙江省交通规划设计院',
          supervisorUnit: '浙江桥梁工程监理公司',
          constructionUnit: '浙江大桥建设工程有限公司',
          buildDate: '2008-12',
          totalLength: '12.5亿元',
          maintainGrade: 'Ⅰ类养护',
          maintainLevel: '特等养护',
          roadGrade: '城市快速路',
          structureType: '悬索桥',
          loadGrade: '公路-Ⅰ级',
          limitLoad: '限载55t',
          checkWidth: 'Ⅲ度',
          skewAngle: '24°',
          bridgeSpans: '6跨',
          spanCombination: '90+120+180+120+90+776',
          deckLength: '398.2㎡',
          bridgeTotalLength: '1280m',
          bridgeTotalWidth: '28.5m',
          carriagewayWidth: '24m',
          sidewalkWidth: '2×2m',
          riverGrade: 'Ⅲ级航道',
          highestWaterLevel: '9.5m',
          normalWaterLevel: '5.2m',
          girderForm: '钢箱梁',
          girderSize: '单箱单室',
          girderCount: '4片',
          crossBeamForm: '钢横梁',
          mainSpanClearance: '18m',
          bridgeClearHeight: '24m',
          archRiseSpanRatio: '1/5',
          bearingType: '球形钢支座',
          bearingCount: '16个',
          deckStructure: '正交异性板',
          deckPavementThickness: '6cm',
          expansionJointType: '模数式伸缩缝',
          expansionJointCount: '8道',
          mainBridgeLongitudinalSlope: '1.5%',
          mainBridgeTransverseSlope: '2%',
          approachBridgeLongitudinalSlope: '1.2%',
          approachBridgeTransverseSlope: '1.5%',
          pierForm: '门形桥墩',
          pierCount: '8个',
          pierHeight: '14m',
          capBeamSize: '180×180cm',
          pierBaseElevation: '-3.2m',
          pierBaseplateSize: '320×240cm',
          pierPileSize: 'φ1400mm',
          pierPileCount: '32根',
          abutmentForm: '重力式桥台',
          abutmentCount: '2个',
          abutmentElevation: '11m',
          abutmentBaseElevation: '-2.5m',
          capSize: '120×100cm',
          abutmentBaseplateSize: '200×150cm',
          abutmentPileSize: 'φ1200mm',
          abutmentPileCount: '12根',
          retainingPlateThickness: '35cm',
          wingWallForm: '八字形墙',
          wingWallLength: '8m',
          collectorSize: '50×30cm',
          collectorCount: '8个',
          drainPipeSize: 'φ100mm',
          drainPipeLength: '120m',
          railingTotalLength: '2560m',
          railingStructure: '钢护栏',
          endColumnSize: '30×40cm',
          bankProtectionType: '浆砌片石护坡',
          approachRetainingWallType: '重力式挡墙',
          attachedPipe: { waterPipe: '有', gasPipe: '有', powerCable: '有', telecomCable: '有' },
        },
      },
      {
        name: '子桥2', structureType: '刚架桥', maintainGrade: 'Ⅰ类养护', span: '420m', length: '920m', width: '26m', buildDate: '2008-12',
        card: {
          unitName: '测试站桥',
          cardName: '子桥2',
          roadName: '中环高架路',
          crossLevel: '跨越钱塘江',
          cardLocation: '杭州市钱塘江中区域',
          manageType: '浙江省水利工程局',
          maintainUnit: '越城区公用事业集团',
          buildUnit: '浙江桥梁工程建设集团',
          designUnit: '浙江省交通规划设计院',
          supervisorUnit: '浙江桥梁工程监理公司',
          constructionUnit: '浙江大桥建设工程有限公司',
          buildDate: '2008-12',
          totalLength: '6200万元',
          maintainGrade: 'Ⅰ类养护',
          maintainLevel: '特等养护',
          roadGrade: '城市快速路',
          structureType: '刚架桥',
          loadGrade: '公路-5',
          spanCount: '5跨',
          spanCombination: '60+90+420+90+60',
          deckLength: '920m',
          bridgeTotalLength: '920m',
          bridgeTotalWidth: '26m',
          carriagewayWidth: '20m',
          sidewalkWidth: '2×2m',
          riverGrade: 'Ⅲ级航道',
          highestWaterLevel: '9.5m',
          normalWaterLevel: '5.2m',
          girderForm: '预应力箱梁',
          girderSize: '单箱单室',
          girderCount: '6片',
          crossBeamForm: '钢筋混凝土横梁',
          mainSpanClearance: '12m',
          bridgeClearHeight: '20m',
          archRiseSpanRatio: '—',
          bearingType: '板式橡胶支座',
          bearingCount: '18个',
          deckStructure: '现浇混凝土',
          deckPavementThickness: '15cm',
          expansionJointCount: '8道',
          mainBridgeLongitudinalSlope: '1%',
          mainBridgeTransverseSlope: '2%',
          approachBridgeLongitudinalSlope: '1%',
          approachBridgeTransverseSlope: '1.5%',
          pierForm: '钢筋混凝土桥墩',
          pierCount: '8个',
          pierHeight: '11m',
          capBeamSize: '160×160cm',
          pierBaseElevation: '-3m',
          pierBaseplateSize: '300×200cm',
          pierPileSize: 'φ1200mm',
          pierPileCount: '28根',
          abutmentForm: '重力式桥台',
          abutmentCount: '2个',
          abutmentElevation: '10m',
          abutmentBaseElevation: '-2.2m',
          capSize: '100×90cm',
          abutmentBaseplateSize: '180×140cm',
          abutmentPileSize: 'φ1100mm',
          abutmentPileCount: '10根',
          retainingPlateThickness: '30cm',
          wingWallLength: '6m',
          collectorCount: '6个',
          drainPipeSize: 'φ80mm',
          drainPipeLength: '80m',
          railingTotalLength: '1840m',
          railingStructure: '钢护栏',
          bankProtectionType: '浆砌片石护坡',
          approachRetainingWallType: '重力式挡墙',
          attachedPipe: { waterPipe: '有', gasPipe: '有', powerCable: '有', telecomCable: '有' },
        },
      },
    ],
    // 检测整改记录（对齐线上）
    detectRecords: [
      { id: 1, name: '测试0622', checkTime: '2026-06-22', detectType: '常规检测', rectType: 'Ⅰ类养护', evalLevel: '合格', rectifyResult: '', rectifyDate: '' },
      { id: 2, name: '测试001', checkTime: '2026-06-18', detectType: '常规检测', rectType: 'Ⅰ类养护', evalLevel: '不合格', rectifyResult: '已完成销号', rectifyDate: '2026-06-25' },
      { id: 3, name: '测试检测', checkTime: '2026-06-10', detectType: '常规检测', rectType: 'Ⅰ类养护', evalLevel: '不合格', rectifyResult: '已完成销号', rectifyDate: '2026-06-10' },
    ],
  },
  {
    key: '2',
    region: '金华市兰溪市',
    name: '金角大桥',
    type: '城市道路桥梁',
    cityClassification: '特大桥',
    structureType: '梁桥',
    buildTime: '2012-06-15',
    span: 820,
    isNavigationBridge: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-10',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '兰溪市交通运输局',
    industryPerson: '陈杰',
    industryContact: '0579-8880001',
    facilityManageUnit: '兰溪市市政管理处',
    facilityManagePerson: '刘伟',
    facilityManageContact: '0579-8880002',
    facilityMaintainUnit: '兰溪市公路养护段',
    facilityMaintainPerson: '周涛',
    facilityMaintainContact: '0579-8880003',
    policeUnit: '兰溪市交警大队',
    policeContact: '吴敏',
    policeContactPhone: '0579-8880004',
    bridgeLocation: '兰溪市金角镇跨兰江',
    isLargeTransportChannel: '是',
  },
  {
    key: '3',
    region: '温州市平阳县',
    name: '雷渡桥',
    type: '城市道路桥梁',
    cityClassification: '小桥',
    structureType: '板桥',
    buildTime: '2015-09-20',
    span: 45,
    isNavigationBridge: false,
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: '合格',
    evalYear: 2023,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-05-08',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '平阳县交通运输局',
    industryPerson: '苏晨',
    industryContact: '0577-6310001',
    facilityManageUnit: '平阳县市政管理处',
    facilityManagePerson: '黄磊',
    facilityManageContact: '0577-6310002',
    facilityMaintainUnit: '平阳县公路养护段',
    facilityMaintainPerson: '曹颖',
    facilityMaintainContact: '0577-6310003',
    policeUnit: '平阳县交警大队',
    policeContact: '薛军',
    policeContactPhone: '0577-6310004',
    bridgeLocation: '平阳县鳌江镇雷渡村',
    isLargeTransportChannel: '否',
  },
  {
    key: '4',
    region: '温州市平阳县',
    name: '杨北北门桥',
    type: '城市道路桥梁',
    cityClassification: '小桥',
    structureType: '板桥',
    buildTime: '2014-03-12',
    span: 38,
    isNavigationBridge: false,
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: '不合格',
    evalYear: 2022,
    dataComplete: false,
    publishStatus: '草稿',
    detectTime: '2025-11-15',
    isOverdue: '已超期',
    status: '在用',
    industryUnit: '平阳县交通运输局',
    industryPerson: '苏晨',
    industryContact: '0577-6310001',
    facilityManageUnit: '平阳县市政管理处',
    facilityManagePerson: '黄磊',
    facilityManageContact: '0577-6310002',
    facilityMaintainUnit: '平阳县公路养护段',
    facilityMaintainPerson: '曹颖',
    facilityMaintainContact: '0577-6310003',
    policeUnit: '平阳县交警大队',
    policeContact: '薛军',
    policeContactPhone: '0577-6310004',
    bridgeLocation: '平阳县昆阳镇杨北社区',
    isLargeTransportChannel: '否',
  },
  {
    key: '5',
    region: '杭州市市辖区',
    name: '古墩路跨线桥',
    type: '城市道路桥梁',
    cityClassification: '高架桥',
    structureType: '梁桥',
    buildTime: '2009-01-01',
    span: 1.1,
    isNavigationBridge: false,
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: '合格',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-06-15',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '杭州市交通运输局',
    industryPerson: '张明',
    industryContact: '0571-88000001',
    facilityManageUnit: '杭州市市政设施管理中心',
    facilityManagePerson: '李强',
    facilityManageContact: '0571-88000002',
    facilityMaintainUnit: '杭州市桥梁养护公司',
    facilityMaintainPerson: '王勇',
    facilityMaintainContact: '0571-88000003',
    policeUnit: '杭州市交警支队',
    policeContact: '赵刚',
    policeContactPhone: '0571-88000004',
    bridgeLocation: '杭州市西湖区古墩路',
    isLargeTransportChannel: '否',
  },
  {
    key: '6',
    region: '杭州市市辖区',
    name: '留石快速路(储鑫路至丰庆路)',
    type: '城市道路桥梁',
    cityClassification: '立交桥',
    structureType: '梁桥',
    buildTime: '2016-07-06',
    span: 6.43,
    isNavigationBridge: false,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-20',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '杭州市交通运输局',
    industryPerson: '张明',
    industryContact: '0571-88000001',
    facilityManageUnit: '杭州市市政设施管理中心',
    facilityManagePerson: '李强',
    facilityManageContact: '0571-88000002',
    facilityMaintainUnit: '杭州市桥梁养护公司',
    facilityMaintainPerson: '王勇',
    facilityMaintainContact: '0571-88000003',
    policeUnit: '杭州市交警支队',
    policeContact: '赵刚',
    policeContactPhone: '0571-88000004',
    bridgeLocation: '杭州市拱墅区留石快速路',
    isLargeTransportChannel: '否',
  },
  {
    key: '7',
    region: '宁波市镇海区',
    name: '甬江大桥',
    type: '城市道路桥梁',
    cityClassification: '特大桥',
    structureType: '斜拉桥',
    buildTime: '2010-10-01',
    span: 980,
    isNavigationBridge: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-08-01',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '镇海区交通运输局',
    industryPerson: '孙磊',
    industryContact: '0574-86200001',
    facilityManageUnit: '镇海区市政设施管理所',
    facilityManagePerson: '钱波',
    facilityManageContact: '0574-86200002',
    facilityMaintainUnit: '镇海区道路养护中心',
    facilityMaintainPerson: '冯涛',
    facilityMaintainContact: '0574-86200003',
    policeUnit: '镇海区交警大队',
    policeContact: '蒋华',
    policeContactPhone: '0574-86200004',
    bridgeLocation: '镇海区跨甬江',
    isLargeTransportChannel: '是',
  },
  {
    key: '8',
    region: '嘉兴市南湖区',
    name: '南湖大桥',
    type: '城市道路桥梁',
    cityClassification: '中桥',
    structureType: '梁桥',
    buildTime: '2013-05-18',
    span: 85,
    isNavigationBridge: false,
    hasMonitorDevice: true,
    hasMonitorFacility: false,
    evalLevel: '合格',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-06-10',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '南湖区交通运输局',
    industryPerson: '程辉',
    industryContact: '0573-8280001',
    facilityManageUnit: '南湖区市政设施管理所',
    facilityManagePerson: '丁宁',
    facilityManageContact: '0573-8280002',
    facilityMaintainUnit: '南湖区道路养护中心',
    facilityMaintainPerson: '魏兵',
    facilityMaintainContact: '0573-8280003',
    policeUnit: '南湖区交警大队',
    policeContact: '任远',
    policeContactPhone: '0573-8280004',
    bridgeLocation: '南湖区南湖景区',
    isLargeTransportChannel: '否',
  },
  {
    key: '9',
    region: '湖州市安吉县',
    name: '递铺港桥',
    type: '城市道路桥梁',
    cityClassification: '小桥',
    structureType: '板桥',
    buildTime: '2018-11-25',
    span: 22,
    isNavigationBridge: false,
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: '合格',
    evalYear: 2023,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-04-05',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '安吉县交通运输局',
    industryPerson: '华强',
    industryContact: '0572-5030001',
    facilityManageUnit: '安吉县市政管理处',
    facilityManagePerson: '方圆',
    facilityManageContact: '0572-5030002',
    facilityMaintainUnit: '安吉县公路养护段',
    facilityMaintainPerson: '董明',
    facilityMaintainContact: '0572-5030003',
    policeUnit: '安吉县交警大队',
    policeContact: '贾磊',
    policeContactPhone: '0572-5030004',
    bridgeLocation: '安吉县递铺街道递铺港',
    isLargeTransportChannel: '否',
  },
  {
    key: '10',
    region: '绍兴市柯桥区',
    name: '瓜渚湖东桥',
    type: '城市道路桥梁',
    cityClassification: '中桥',
    structureType: '拱桥',
    buildTime: '2011-08-10',
    span: 72,
    isNavigationBridge: false,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-15',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '柯桥区交通运输局',
    industryPerson: '高峰',
    industryContact: '0575-84100001',
    facilityManageUnit: '柯桥区市政设施管理所',
    facilityManagePerson: '唐杰',
    facilityManageContact: '0575-84100002',
    facilityMaintainUnit: '柯桥区道路养护公司',
    facilityMaintainPerson: '邓超',
    facilityMaintainContact: '0575-84100003',
    policeUnit: '柯桥区交警大队',
    policeContact: '曾鸣',
    policeContactPhone: '0575-84100004',
    bridgeLocation: '柯桥区瓜渚湖东岸',
    isLargeTransportChannel: '否',
  },
  {
    key: '11',
    region: '丽水市缙云县',
    name: '好溪大桥',
    type: '城市道路桥梁',
    cityClassification: '大桥',
    structureType: '梁桥',
    buildTime: '2016-04-20',
    span: 320,
    isNavigationBridge: false,
    hasMonitorDevice: true,
    hasMonitorFacility: false,
    evalLevel: '合格',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-05-20',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '缙云县交通运输局',
    industryPerson: '陈杰',
    industryContact: '0578-3120001',
    facilityManageUnit: '缙云县市政管理处',
    facilityManagePerson: '刘伟',
    facilityManageContact: '0578-3120002',
    facilityMaintainUnit: '缙云县公路养护段',
    facilityMaintainPerson: '周涛',
    facilityMaintainContact: '0578-3120003',
    policeUnit: '缙云县交警大队',
    policeContact: '吴敏',
    policeContactPhone: '0578-3120004',
    bridgeLocation: '缙云县五云镇跨好溪',
    isLargeTransportChannel: '否',
  },
  {
    key: '12',
    region: '台州市椒江区',
    name: '椒江大桥',
    type: '城市道路桥梁',
    cityClassification: '特大桥',
    structureType: '梁桥',
    buildTime: '2009-12-28',
    span: 1150,
    isNavigationBridge: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-06-25',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '椒江区交通运输局',
    industryPerson: '毛勇',
    industryContact: '0576-8880001',
    facilityManageUnit: '椒江区市政设施管理所',
    facilityManagePerson: '段飞',
    facilityManageContact: '0576-8880002',
    facilityMaintainUnit: '椒江区道路养护中心',
    facilityMaintainPerson: '雷鸣',
    facilityMaintainContact: '0576-8880003',
    policeUnit: '椒江区交警大队',
    policeContact: '文斌',
    policeContactPhone: '0576-8880004',
    bridgeLocation: '椒江区跨椒江',
    isLargeTransportChannel: '是',
  },
  {
    key: '13',
    region: '衢州市柯城区',
    name: '衢江大桥',
    type: '城市道路桥梁',
    cityClassification: '其他',
    structureType: '梁桥',
    buildTime: '2014-07-15',
    span: 580,
    isNavigationBridge: true,
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: '合格',
    evalYear: 2023,
    dataComplete: false,
    publishStatus: '草稿',
    detectTime: '2025-12-20',
    isOverdue: '已超期',
    status: '在建',
    industryUnit: '柯城区交通运输局',
    industryPerson: '毕华',
    industryContact: '0570-3030001',
    facilityManageUnit: '柯城区市政管理处',
    facilityManagePerson: '颜青',
    facilityManageContact: '0570-3030002',
    facilityMaintainUnit: '柯城区公路养护段',
    facilityMaintainPerson: '霍亮',
    facilityMaintainContact: '0570-3030003',
    policeUnit: '柯城区交警大队',
    policeContact: '阮超',
    policeContactPhone: '0570-3030004',
    bridgeLocation: '柯城区跨衢江',
    isLargeTransportChannel: '否',
  },
  {
    key: '14',
    region: '舟山市定海区',
    name: '定海东方桥',
    type: '城市道路桥梁',
    cityClassification: '中桥',
    structureType: '梁桥',
    buildTime: '2017-06-08',
    span: 68,
    isNavigationBridge: false,
    hasMonitorDevice: true,
    hasMonitorFacility: false,
    evalLevel: '合格',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-03-18',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '定海区交通运输局',
    industryPerson: '于海',
    industryContact: '0580-2020001',
    facilityManageUnit: '定海区市政设施管理中心',
    facilityManagePerson: '安琪',
    facilityManageContact: '0580-2020002',
    facilityMaintainUnit: '定海区道路养护公司',
    facilityMaintainPerson: '马骏',
    facilityMaintainContact: '0580-2020003',
    policeUnit: '定海区交警大队',
    policeContact: '乐威',
    policeContactPhone: '0580-2020004',
    bridgeLocation: '定海区城东街道',
    isLargeTransportChannel: '否',
  },
  {
    key: '15',
    region: '金华市义乌市',
    name: '义乌江大桥',
    type: '城市道路桥梁',
    cityClassification: '大桥',
    structureType: '梁桥',
    buildTime: '2015-10-30',
    span: 420,
    isNavigationBridge: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-28',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '义乌市交通运输局',
    industryPerson: '胡杰',
    industryContact: '0579-8550001',
    facilityManageUnit: '义乌市市政设施管理中心',
    facilityManagePerson: '余涛',
    facilityManageContact: '0579-8550002',
    facilityMaintainUnit: '义乌市道路养护公司',
    facilityMaintainPerson: '吕波',
    facilityMaintainContact: '0579-8550003',
    policeUnit: '义乌市交警大队',
    policeContact: '施峰',
    policeContactPhone: '0579-8550004',
    bridgeLocation: '义乌市跨义乌江',
    isLargeTransportChannel: '是',
  },
  {
    key: '16',
    region: '杭州市萧山区',
    name: '钱塘江三桥（西兴大桥）',
    type: '城市道路桥梁',
    cityClassification: '特大桥',
    structureType: '斜拉桥',
    buildTime: '2007-01-20',
    span: 1280,
    isNavigationBridge: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: '合格',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-08-05',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '杭州市交通运输局',
    industryPerson: '张明',
    industryContact: '0571-88000001',
    facilityManageUnit: '杭州市市政设施管理中心',
    facilityManagePerson: '李强',
    facilityManageContact: '0571-88000002',
    facilityMaintainUnit: '杭州市桥梁养护公司',
    facilityMaintainPerson: '王勇',
    facilityMaintainContact: '0571-88000003',
    policeUnit: '杭州市交警支队',
    policeContact: '赵刚',
    policeContactPhone: '0571-88000004',
    bridgeLocation: '杭州市萧山区跨钱塘江',
    isLargeTransportChannel: '是',
  },
]

// 自定义显示顺序：测试-复兴大桥第1条，人行天桥随意穿插
const displayOrder: Record<string, number> = {
  '1': 1, '17': 2, '2': 3, '3': 4, '18': 5,
  '4': 6, '5': 7, '19': 8, '6': 9, '7': 10,
  '20': 11, '8': 12, '9': 13, '21': 14, '10': 15,
  '11': 16, '12': 17, '13': 18, '14': 19, '15': 20, '16': 21,
}

// 模拟获取桥梁列表
export function getBridgeList(
  params: BridgeSearchParams
): Promise<PaginationResponse<BridgeItem>> {
  return new Promise((resolve) => {
    setTimeout(() => {
      let filteredList = [...mockBridges]

      // 按自定义顺序排序
      filteredList.sort((a, b) => {
        const oa = displayOrder[a.key] ?? 999
        const ob = displayOrder[b.key] ?? 999
        return oa - ob
      })

      // 筛选
      if (params.region) {
        filteredList = filteredList.filter((item) => item.region.includes(params.region!))
      }
      if (params.name) {
        filteredList = filteredList.filter((item) => item.name.includes(params.name!))
      }
      if (params.type) {
        filteredList = filteredList.filter((item) => item.type === params.type)
      }
      if (params.cityClassification) {
        filteredList = filteredList.filter((item) => item.cityClassification === params.cityClassification)
      }
      if (params.evalLevel) {
        filteredList = filteredList.filter((item) => item.evalLevel === params.evalLevel)
      }
      if (params.isNavigationBridge) {
        const val = params.isNavigationBridge === '是'
        filteredList = filteredList.filter((item) => item.isNavigationBridge === val)
      }
      if (params.status) {
        filteredList = filteredList.filter((item) => item.status === params.status)
      }
      if (params.dataComplete) {
        const val = params.dataComplete === '是'
        filteredList = filteredList.filter((item) => item.dataComplete === val)
      }
      if (params.publishStatus) {
        filteredList = filteredList.filter((item) => item.publishStatus === params.publishStatus)
      }
      if (params.isOverdue) {
        filteredList = filteredList.filter((item) => item.isOverdue === params.isOverdue)
      }

      // 分页
      const total = filteredList.length
      const page = params.page || 1
      const pageSize = params.pageSize || 10
      const start = (page - 1) * pageSize
      const end = start + pageSize
      const list = filteredList.slice(start, end)

      resolve({
        list,
        total,
        page,
        pageSize,
      })
    }, 500) // 模拟网络延迟
  })
}

// 模拟删除桥梁
export function deleteBridge(key: string): Promise<boolean> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true)
    }, 300)
  })
}

// 模拟批量删除
export function batchDeleteBridge(keys: string[]): Promise<boolean> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true)
    }, 500)
  })
}

// 模拟获取桥梁详情
export function getBridgeDetail(key: string): Promise<BridgeDetail> {
  return new Promise((resolve) => {
    setTimeout(() => {
      // 查找对应的桥梁
      const bridge = mockBridges.find(item => item.key === key)
      
      if (bridge) {
        resolve({
          key: bridge.key,
          region: bridge.region,
          name: bridge.name,
          location: bridge.bridgeLocation || '浙江省杭州市市辖区',
          buildTime: bridge.buildTime,
          type: bridge.type,
          industryManager: bridge.industryUnit || '杭州市交通运输局',
          responsiblePerson: bridge.industryPerson || '张三',
          contactPhone: bridge.industryContact || '0571-88888888',
          operationUnit: bridge.facilityManageUnit || '杭州市市政设施管理中心',
          siteSupervisor: bridge.facilityManagePerson || '李四',
          supervisorContact: bridge.facilityManageContact || '13800138000',
          siteResponsiblePerson: bridge.facilityMaintainPerson || '王五',
          responsibleContact: bridge.facilityMaintainContact || '13900139000',
          isNavigationBridge: bridge.isNavigationBridge,
          hasAntiCollision: false,
          hasShipCollisionWarning: false,
          hasMonitoring: bridge.hasMonitorDevice,
          hasMonitorFacility: bridge.hasMonitorFacility,
        })
      } else {
        // 默认值
        resolve({
          key,
          region: '浙江省 / 杭州市 / 市辖区',
          name: '古墩路跨线桥',
          location: '浙江省杭州市市辖区古墩路',
          buildTime: '2009-01-01',
          type: '城市道路桥梁',
          industryManager: '',
          responsiblePerson: '',
          contactPhone: '',
          operationUnit: '',
          siteSupervisor: '',
          supervisorContact: '',
          siteResponsiblePerson: '',
          responsibleContact: '',
          isNavigationBridge: false,
          hasAntiCollision: false,
          hasShipCollisionWarning: false,
          hasMonitoring: false,
          hasMonitorFacility: false,
        })
      }
    }, 300)
  })
}

// 地区选项 — 浙江省11个地市的区县
export const regionOptions = [
  { label: '杭州市市辖区', value: '杭州市市辖区' },
  { label: '杭州市余杭区', value: '杭州市余杭区' },
  { label: '杭州市拱墅区', value: '杭州市拱墅区' },
  { label: '杭州市西湖区', value: '杭州市西湖区' },
  { label: '杭州市滨江区', value: '杭州市滨江区' },
  { label: '杭州市萧山区', value: '杭州市萧山区' },
  { label: '宁波市市辖区', value: '宁波市市辖区' },
  { label: '宁波市镇海区', value: '宁波市镇海区' },
  { label: '温州市平阳县', value: '温州市平阳县' },
  { label: '嘉兴市南湖区', value: '嘉兴市南湖区' },
  { label: '嘉兴市嘉兴港区', value: '嘉兴市嘉兴港区' },
  { label: '湖州市南太湖新区', value: '湖州市南太湖新区' },
  { label: '湖州市安吉县', value: '湖州市安吉县' },
  { label: '绍兴市柯桥区', value: '绍兴市柯桥区' },
  { label: '金华市兰溪市', value: '金华市兰溪市' },
  { label: '金华市义乌市', value: '金华市义乌市' },
  { label: '丽水市缙云县', value: '丽水市缙云县' },
  { label: '台州市椒江区', value: '台州市椒江区' },
  { label: '衢州市柯城区', value: '衢州市柯城区' },
  { label: '舟山市定海区', value: '舟山市定海区' },
]

// 桥梁类型选项 — 对齐导则：城市道路桥梁 + 人行天桥（两大类）
export const bridgeTypeOptions = [
  { label: '城市道路桥梁', value: '城市道路桥梁', group: '城市道路桥梁' },
  { label: '人行天桥', value: '人行天桥', group: '人行天桥' },
]

// 城市道路桥梁分类选项
export const bridgeClassificationOptions = [
  { label: '特大桥', value: '特大桥' },
  { label: '大桥', value: '大桥' },
  { label: '中桥', value: '中桥' },
  { label: '小桥', value: '小桥' },
  { label: '高架桥', value: '高架桥' },
  { label: '立交桥', value: '立交桥' },
  { label: '其他', value: '其他' },
]

// 综合评价等级选项
export const evalLevelOptions = [
  { label: 'A', value: 'A' },
  { label: 'B', value: 'B' },
  { label: 'C', value: 'C' },
  { label: 'D', value: 'D' },
  { label: 'E', value: 'E' },
]

// 是否涉航桥梁选项
export const isNavigationBridgeOptions = [
  { label: '是', value: '是' },
  { label: '否', value: '否' },
]

// 发布状态选项
export const publishStatusOptions = [
  { label: '草稿', value: '草稿' },
  { label: '已发布', value: '已发布' },
]

// 检测是否超期选项
export const isOverdueOptions = [
  { label: '未超期', value: '未超期' },
  { label: '已超期', value: '已超期' },
]

// 数据是否完善选项
export const dataCompleteOptions = [
  { label: '是', value: '是' },
  { label: '否', value: '否' },
]

// 状态选项
export const statusOptions = [
  { label: '在用', value: '在用' },
  { label: '在建', value: '在建' },
  { label: '停用', value: '停用' },
]
