import type { TunnelItem, TunnelSearchParams } from '@/types/tunnel'

// Mock隧道数据 — 使用线上系统真实地名
const mockTunnels: TunnelItem[] = [
  {
    key: '1',
    region: '杭州市市辖区',
    name: '测试隧道2',
    type: '城市道路隧道',
    cityClassification: '中隧道(500m<L≤1000m)',
    buildTime: '2015-06-01',
    isUnderground: false,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-08-13',
    isOverdue: '未超期',
    status: '在用',
    liningType: '测试隧道2复合式衬砌',
    hasMultiUnit: false,
    industryUnit: '浙江省-省政府机构-省建设厅-城市建设处',
    industryPerson: '王雨晴',
    industryContact: '17360312375',
    facilityManageUnit: '浙江省-省政府机构-省建设厅-城市建设处',
    facilityManagePerson: '王雨晴',
    facilityManageContact: '17360312375',
    facilityMaintainUnit: '养护单位001',
    facilityMaintainPerson: '测试余杭',
    facilityMaintainContact: '15678945678',
    policeUnit: '杭州市公安局交警支队',
    policeContact: '李俊琦',
    policeContactPhone: '13567194276',
    tunnelLocation: '杭州市市辖区测试路段',
    // 隧道资料卡（hasMultiUnit=否 → 单一资料卡）
    cardData: {
      name: '测试隧道2',
      roadName: '测试路段',
      district: '杭州市市辖区',
      manageUnit: '浙江省-省政府机构-省建设厅-城市建设处',
      maintainUnit: '养护单位001',
      crossOver: '河',
      buildDate: '2015-06-01',
      buildUnit: '中铁十四局集团',
      totalCost: '12000',
      surveyUnit: '浙江省交通勘察设计院',
      maintainCategory: '一类',
      designUnit: '浙江省交通规划设计研究院',
      maintainGrade: '一级',
      superviseUnit: '浙江工程建设监理公司',
      roadGrade: '主干路',
      constructUnit: '中铁十四局集团',
      designLanes: '双向四车道',
      designLoad: '公路-I级',
      designSpeed: '60',
      designFlow: '2400',
      emergencyPhone: '有',
      roadCrossSection: '2.5+3.5+3.5+2.5',
      motorPavement: '沥青混凝土',
      nonMotorPavement: '沥青混凝土',
      sidewalkPavement: '预制砖',
      drivewayLengthSingle: '850',
      drivewayWidth: '10.5',
      drivewayLength: '850',
      sidewalkWidth: '1.0',
      motorMaxSlope: '1.5%',
      nonMotorMaxSlope: '1.2%',
      crossSlope: '1.5%',
      waterproofGrade: '二级',
      geology: 'IV级围岩',
      liningType: '复合式衬砌',
      liningThickness: '45',
      portalForm: '削竹式',
      ceilingDecoration: '铝板',
      ceilingDecorationArea: '8500',
      wallDecoration: '瓷砖',
      wallDecorationArea: '6800',
      crashWallDecoration: '涂料',
      crashWallDecorationArea: '1700',
      motorClearHeight: '4.5',
      nonMotorClearHeight: '2.5',
      designFloodLevel: '8.5',
      sewagePumpCount: '1',
      rainPumpCount: '2',
      railingForm: '钢栏杆',
      railingLength: '850',
      drainForm: '明沟',
      drainLength: '850',
      topDrainForm: '截水沟',
      overview: '测试隧道2位于杭州市市辖区测试路段，全长850米，2015年6月建成通车。',
      review: '张工', check: '李工', drafting: '王工', cardDate: '2015-06-20',
    },
    // 检测整改记录（对齐线上）
    detectRecords: [
      { id: 1, name: '测试检测yan', checkTime: '2026-08-13', type: 'A', grade: 'A', result: '' },
      { id: 2, name: '测试检测', checkTime: '2026-06-26', type: 'A', grade: 'A', result: '' },
    ],
  },
  {
    key: '2',
    region: '杭州市市辖区',
    name: '测试-余杭塘路隧道',
    type: '城市道路隧道',
    cityClassification: '中隧道(500m<L≤1000m)',
    buildTime: '2016-09-15',
    isUnderground: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-06-26',
    isOverdue: '未超期',
    status: '在用',
    liningType: '钢筋混凝土箱涵',
    hasMultiUnit: true,
    industryUnit: '浙江省-省政府机构-省建设厅-城市建设处',
    industryPerson: '王雨晴',
    industryContact: '17360312375',
    facilityManageUnit: '浙江省-省政府机构-省建设厅-城市建设处',
    facilityManagePerson: '王雨晴',
    facilityManageContact: '17360312375',
    facilityMaintainUnit: '越城区公用事业集团',
    facilityMaintainPerson: '张琦峰',
    facilityMaintainContact: '15268470922',
    policeUnit: '杭州市公安局交警支队',
    policeContact: '李俊琦',
    policeContactPhone: '13567194276',
    tunnelLocation: 'MULTILINESTRING((120.03884385142806 30.298636704404792,120.04101688844115 30.298738062751063,120.0427598 30.2986759),(120.0427598 30.2986759,120.0429798 30.298664,120.0453386 30.2985364,120.0475227 30.2983896,120.0484522 30.2983407),(120.0484522 30.2983407,120.0505827 30.2982441),(120.0292114 30.2964407,120.0294809 30.2965773,120.0298742 30.2967726,120.0314277 30.2975169,120.0320085 30.297745,120.0325591 30.29793,120.0328976 30.2980234,120.033174 30.298077,120.03436 30.2982878,120.035688 30.2984055,120.0388902 30.2986401,120.0391108 30.2986496,120.0395781 30.2986696,120.0409545 30.2987387,120.0416594 30.2987315,120.0427598 30.2986759))',
    // 隧道单元资料卡（hasMultiUnit=是 → 双单元）
    tunnelUnits: [
      {
        name: '测试-余杭塘路隧道（单元1）',
        roadName: '余杭塘路',
        district: '杭州市市辖区',
        manageUnit: '浙江省-省政府机构-省建设厅-城市建设处',
        maintainUnit: '越城区公用事业集团',
        crossOver: '路',
        buildDate: '2016-09-15',
        buildUnit: '中铁十四局集团',
        totalCost: '8500',
        surveyUnit: '浙江省交通勘察设计院',
        maintainCategory: '一类',
        designUnit: '浙江省交通规划设计研究院',
        maintainGrade: '一级',
        superviseUnit: '浙江工程建设监理公司',
        roadGrade: '主干路',
        constructUnit: '中铁十四局集团',
        designLanes: '双向四车道',
        designLoad: '公路-I级',
        designSpeed: '60',
        designFlow: '2400',
        emergencyPhone: '有',
        roadCrossSection: '2.5+3.5+3.5+2.5',
        motorPavement: '沥青混凝土',
        nonMotorPavement: '沥青混凝土',
        sidewalkPavement: '预制砖',
        drivewayLengthSingle: '420',
        drivewayWidth: '10.5',
        drivewayLength: '420',
        sidewalkWidth: '1.0',
        motorMaxSlope: '1.5%',
        nonMotorMaxSlope: '1.2%',
        crossSlope: '1.5%',
        waterproofGrade: '二级',
        geology: 'IV级围岩',
        liningType: '钢筋混凝土箱涵',
        liningThickness: '45',
        portalForm: '削竹式',
        ceilingDecoration: '铝板',
        ceilingDecorationArea: '4200',
        wallDecoration: '瓷砖',
        wallDecorationArea: '3400',
        crashWallDecoration: '涂料',
        crashWallDecorationArea: '850',
        motorClearHeight: '4.5',
        nonMotorClearHeight: '2.5',
        designFloodLevel: '8.5',
        sewagePumpCount: '1',
        rainPumpCount: '2',
        railingForm: '钢栏杆',
        railingLength: '420',
        drainForm: '明沟',
        drainLength: '420',
        topDrainForm: '截水沟',
        overview: '测试-余杭塘路隧道单元1，全长420米，2016年9月建成通车。',
        review: '张工', check: '李工', drafting: '王工', cardDate: '2016-09-25',
      },
      {
        name: '测试-余杭塘路隧道（单元2）',
        roadName: '余杭塘路',
        district: '杭州市市辖区',
        manageUnit: '浙江省-省政府机构-省建设厅-城市建设处',
        maintainUnit: '越城区公用事业集团',
        crossOver: '路',
        buildDate: '2016-09-15',
        buildUnit: '中铁十四局集团',
        totalCost: '8500',
        surveyUnit: '浙江省交通勘察设计院',
        maintainCategory: '一类',
        designUnit: '浙江省交通规划设计研究院',
        maintainGrade: '一级',
        superviseUnit: '浙江工程建设监理公司',
        roadGrade: '主干路',
        constructUnit: '中铁十四局集团',
        designLanes: '双向四车道',
        designLoad: '公路-I级',
        designSpeed: '60',
        designFlow: '2400',
        emergencyPhone: '有',
        roadCrossSection: '2.5+3.5+3.5+2.5',
        motorPavement: '沥青混凝土',
        nonMotorPavement: '沥青混凝土',
        sidewalkPavement: '预制砖',
        drivewayLengthSingle: '420',
        drivewayWidth: '10.5',
        drivewayLength: '420',
        sidewalkWidth: '1.0',
        motorMaxSlope: '1.5%',
        nonMotorMaxSlope: '1.2%',
        crossSlope: '1.5%',
        waterproofGrade: '二级',
        geology: 'IV级围岩',
        liningType: '钢筋混凝土箱涵',
        liningThickness: '45',
        portalForm: '削竹式',
        ceilingDecoration: '铝板',
        ceilingDecorationArea: '4200',
        wallDecoration: '瓷砖',
        wallDecorationArea: '3400',
        crashWallDecoration: '涂料',
        crashWallDecorationArea: '850',
        motorClearHeight: '4.5',
        nonMotorClearHeight: '2.5',
        designFloodLevel: '8.5',
        sewagePumpCount: '1',
        rainPumpCount: '2',
        railingForm: '钢栏杆',
        railingLength: '420',
        drainForm: '明沟',
        drainLength: '420',
        topDrainForm: '截水沟',
        overview: '测试-余杭塘路隧道单元2，全长420米，2016年9月建成通车。',
        review: '陈工', check: '赵工', drafting: '孙工', cardDate: '2016-09-25',
      },
    ],
    // 检测整改记录（对齐线上）
    detectRecords: [
      { id: 1, name: '测试检测', checkTime: '2026-06-26', type: 'A', grade: 'D', result: 'D级已销号' },
      { id: 2, name: '测试检测', checkTime: '2026-06-25', type: 'A', grade: 'D', result: '' },
    ],
  },
  {
    key: '3',
    region: '嘉兴市南湖区',
    name: '庆丰路隧道',
    type: '城市道路隧道',
    cityClassification: '中隧道',
    buildTime: '2019-03-20',
    isUnderground: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-10',
    isOverdue: '未超期',
    status: '在用',
    liningType: '复合式衬砌',
    hasMultiUnit: false,
    industryUnit: '南湖区交通运输局',
    industryPerson: '程辉',
    industryContact: '0573-8280001',
    facilityManageUnit: '南湖区市政设施管理所',
    facilityManagePerson: '丁宁',
    facilityManageContact: '0573-8280002',
    facilityMaintainUnit: '南湖区道路养护中心',
    facilityMaintainPerson: '魏兵',
    facilityMaintainContact: '0573-8280003',
    policeUnit: '南湖区交警大队',
    policeContact: '任远',
    policeContactPhone: '0573-8280004',
    tunnelLocation: '嘉兴市南湖区庆丰路',
    cardData: {
      name: '庆丰路隧道',
      roadName: '庆丰路路',
      district: '嘉兴市南湖区',
      manageUnit: '南湖区市政设施管理所',
      maintainUnit: '南湖区道路养护中心',
      crossOver: '路',
      buildDate: '2019-03-20',
      buildUnit: '中铁隧道工程局集团',
      totalCost: '1020000',
      surveyUnit: '浙江省交通勘察设计院',
      maintainCategory: '一类',
      designUnit: '浙江省交通规划设计研究院',
      maintainGrade: '一级',
      superviseUnit: '浙江工程建设监理公司',
      roadGrade: '主干路',
      constructUnit: '中铁隧道工程局集团',
      designLanes: '双向四车道',
      designLoad: '公路-I级',
      designSpeed: '60',
      designFlow: '2400',
      emergencyPhone: '有',
      roadCrossSection: '2.5+3.5+3.5+2.5',
      motorPavement: '沥青混凝土',
      nonMotorPavement: '沥青混凝土',
      sidewalkPavement: '预制砖',
      drivewayLengthSingle: '680',
      drivewayWidth: '10.5',
      drivewayLength: '680',
      sidewalkWidth: '1.0',
      motorMaxSlope: '1.5%',
      nonMotorMaxSlope: '1.2%',
      crossSlope: '1.5%',
      waterproofGrade: '二级',
      geology: 'IV级围岩',
      liningType: '复合式衬砌',
      liningThickness: '45',
      portalForm: '削竹式',
      ceilingDecoration: '铝板',
      ceilingDecorationArea: '6800',
      wallDecoration: '瓷砖',
      wallDecorationArea: '5440',
      crashWallDecoration: '涂料',
      crashWallDecorationArea: '1360',
      motorClearHeight: '4.5',
      nonMotorClearHeight: '2.5',
      designFloodLevel: '8.5',
      sewagePumpCount: '1',
      rainPumpCount: '2',
      railingForm: '钢栏杆',
      railingLength: '680',
      drainForm: '明沟',
      drainLength: '680',
      topDrainForm: '截水沟',
      overview: '庆丰路隧道位于嘉兴市南湖区，全长680米，2019-03-20建成通车。',
      review: '张工',
      check: '李工',
      drafting: '王工',
      cardDate: '2026-07-10',
    },
    detectRecords: [
      { id: 1, name: '定期检查', checkTime: '2026-07-10', type: 'A', grade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-07-01', type: 'A', grade: 'A', result: '' },
    ],

  },
  {
    key: '4',
    region: '金华市义乌市',
    name: '城北路下穿隧道',
    type: '城市道路隧道',
    cityClassification: '短隧道',
    buildTime: '2020-07-08',
    isUnderground: true,
    hasMonitorDevice: true,
    hasMonitorFacility: false,
    evalLevel: 'A',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-05-15',
    isOverdue: '未超期',
    status: '在用',
    liningType: '复合式衬砌',
    hasMultiUnit: false,
    industryUnit: '义乌市交通运输局',
    industryPerson: '胡杰',
    industryContact: '0579-8550001',
    facilityManageUnit: '义乌市市政设施管理中心',
    facilityManagePerson: '余涛',
    facilityManageContact: '0579-8550002',
    facilityMaintainUnit: '义乌市道路养护公司',
    facilityMaintainPerson: '吕波',
    facilityMaintainContact: '0579-8550003',
    policeUnit: '义乌市交警大队',
    policeContact: '施峰',
    policeContactPhone: '0579-8550004',
    tunnelLocation: '义乌市城北路下穿段',
    cardData: {
      name: '城北路下穿隧道',
      roadName: '城北路路路',
      district: '金华市义乌市',
      manageUnit: '义乌市市政设施管理中心',
      maintainUnit: '义乌市道路养护公司',
      crossOver: '路',
      buildDate: '2020-07-08',
      buildUnit: '中铁隧道工程局集团',
      totalCost: '480000',
      surveyUnit: '浙江省交通勘察设计院',
      maintainCategory: '一类',
      designUnit: '浙江省交通规划设计研究院',
      maintainGrade: '一级',
      superviseUnit: '浙江工程建设监理公司',
      roadGrade: '次干路',
      constructUnit: '中铁隧道工程局集团',
      designLanes: '双向四车道',
      designLoad: '公路-I级',
      designSpeed: '50',
      designFlow: '1800',
      emergencyPhone: '有',
      roadCrossSection: '2.5+3.5+3.5+2.5',
      motorPavement: '沥青混凝土',
      nonMotorPavement: '沥青混凝土',
      sidewalkPavement: '预制砖',
      drivewayLengthSingle: '320',
      drivewayWidth: '8.0',
      drivewayLength: '320',
      sidewalkWidth: '1.0',
      motorMaxSlope: '1.5%',
      nonMotorMaxSlope: '1.2%',
      crossSlope: '1.5%',
      waterproofGrade: '二级',
      geology: 'IV级围岩',
      liningType: '复合式衬砌',
      liningThickness: '45',
      portalForm: '削竹式',
      ceilingDecoration: '铝板',
      ceilingDecorationArea: '3200',
      wallDecoration: '瓷砖',
      wallDecorationArea: '2560',
      crashWallDecoration: '涂料',
      crashWallDecorationArea: '640',
      motorClearHeight: '4.5',
      nonMotorClearHeight: '2.5',
      designFloodLevel: '8.5',
      sewagePumpCount: '1',
      rainPumpCount: '2',
      railingForm: '钢栏杆',
      railingLength: '320',
      drainForm: '明沟',
      drainLength: '320',
      topDrainForm: '截水沟',
      overview: '城北路下穿隧道位于金华市义乌市，全长320米，2020-07-08建成通车。',
      review: '张工',
      check: '李工',
      drafting: '王工',
      cardDate: '2026-05-15',
    },
    detectRecords: [
      { id: 1, name: '定期检查', checkTime: '2026-05-15', type: 'A', grade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-05-01', type: 'A', grade: 'A', result: '' },
    ],

  },
  {
    key: '5',
    region: '湖州市安吉县',
    name: '禹山坞隧道',
    type: '城市道路隧道',
    cityClassification: '长隧道',
    buildTime: '2017-11-12',
    isUnderground: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'B',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-04-20',
    isOverdue: '未超期',
    status: '在用',
    liningType: '复合式衬砌',
    hasMultiUnit: true,
    industryUnit: '安吉县交通运输局',
    industryPerson: '华强',
    industryContact: '0572-5030001',
    facilityManageUnit: '安吉县市政管理处',
    facilityManagePerson: '方圆',
    facilityManageContact: '0572-5030002',
    facilityMaintainUnit: '安吉县公路养护段',
    facilityMaintainPerson: '董明',
    facilityMaintainContact: '0572-5030003',
    policeUnit: '安吉县交警大队',
    policeContact: '贾磊',
    policeContactPhone: '0572-5030004',
    tunnelLocation: '安吉县禹山坞段',
    tunnelUnits: [
      {
        name: '禹山坞隧道（单元1）',
        roadName: '禹山坞路',
        district: '湖州市安吉县',
        manageUnit: '安吉县市政管理处',
        maintainUnit: '安吉县公路养护段',
        crossOver: '路',
        buildDate: '2017-11-12',
        buildUnit: '中铁隧道工程局集团',
        totalCost: '1920000',
        surveyUnit: '浙江省交通勘察设计院',
        maintainCategory: '一类',
        designUnit: '浙江省交通规划设计研究院',
        maintainGrade: '一级',
        superviseUnit: '浙江工程建设监理公司',
        roadGrade: '快速路',
        constructUnit: '中铁隧道工程局集团',
        designLanes: '双向六车道',
        designLoad: '公路-I级',
        designSpeed: '80',
        designFlow: '3600',
        emergencyPhone: '有',
        roadCrossSection: '2.5+3.75+3.75+3.75+3.75+2.5',
        motorPavement: '沥青混凝土',
        nonMotorPavement: '沥青混凝土',
        sidewalkPavement: '预制砖',
        drivewayLengthSingle: '640',
        drivewayWidth: '15.5',
        drivewayLength: '640',
        sidewalkWidth: '1.0',
        motorMaxSlope: '1.5%',
        nonMotorMaxSlope: '1.2%',
        crossSlope: '1.5%',
        waterproofGrade: '二级',
        geology: 'IV级围岩',
        liningType: '复合式衬砌',
        liningThickness: '45',
        portalForm: '削竹式',
        ceilingDecoration: '铝板',
        ceilingDecorationArea: '6400',
        wallDecoration: '瓷砖',
        wallDecorationArea: '5120',
        crashWallDecoration: '涂料',
        crashWallDecorationArea: '1280',
        motorClearHeight: '4.5',
        nonMotorClearHeight: '2.5',
        designFloodLevel: '8.5',
        sewagePumpCount: '1',
        rainPumpCount: '2',
        railingForm: '钢栏杆',
        railingLength: '640',
        drainForm: '明沟',
        drainLength: '640',
        topDrainForm: '截水沟',
        overview: '禹山坞隧道单元1，全长640米，2017-11-12建成通车。',
        review: '张工',
        check: '李工',
        drafting: '王工',
        cardDate: '2026-04-20',
      },
      {
        name: '禹山坞隧道（单元2）',
        roadName: '禹山坞路',
        district: '湖州市安吉县',
        manageUnit: '安吉县市政管理处',
        maintainUnit: '安吉县公路养护段',
        crossOver: '路',
        buildDate: '2017-11-12',
        buildUnit: '中铁隧道工程局集团',
        totalCost: '1920000',
        surveyUnit: '浙江省交通勘察设计院',
        maintainCategory: '一类',
        designUnit: '浙江省交通规划设计研究院',
        maintainGrade: '一级',
        superviseUnit: '浙江工程建设监理公司',
        roadGrade: '快速路',
        constructUnit: '中铁隧道工程局集团',
        designLanes: '双向六车道',
        designLoad: '公路-I级',
        designSpeed: '80',
        designFlow: '3600',
        emergencyPhone: '有',
        roadCrossSection: '2.5+3.75+3.75+3.75+3.75+2.5',
        motorPavement: '沥青混凝土',
        nonMotorPavement: '沥青混凝土',
        sidewalkPavement: '预制砖',
        drivewayLengthSingle: '640',
        drivewayWidth: '15.5',
        drivewayLength: '640',
        sidewalkWidth: '1.0',
        motorMaxSlope: '1.5%',
        nonMotorMaxSlope: '1.2%',
        crossSlope: '1.5%',
        waterproofGrade: '二级',
        geology: 'IV级围岩',
        liningType: '复合式衬砌',
        liningThickness: '45',
        portalForm: '削竹式',
        ceilingDecoration: '铝板',
        ceilingDecorationArea: '6400',
        wallDecoration: '瓷砖',
        wallDecorationArea: '5120',
        crashWallDecoration: '涂料',
        crashWallDecorationArea: '1280',
        motorClearHeight: '4.5',
        nonMotorClearHeight: '2.5',
        designFloodLevel: '8.5',
        sewagePumpCount: '1',
        rainPumpCount: '2',
        railingForm: '钢栏杆',
        railingLength: '640',
        drainForm: '明沟',
        drainLength: '640',
        topDrainForm: '截水沟',
        overview: '禹山坞隧道单元2，全长640米，2017-11-12建成通车。',
        review: '陈工',
        check: '赵工',
        drafting: '孙工',
        cardDate: '2026-04-20',
      },
    ],
    detectRecords: [
      { id: 1, name: '定期检查', checkTime: '2026-04-20', type: 'B', grade: 'B', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-04-01', type: 'B', grade: 'B', result: '' },
    ],

  },
  {
    key: '6',
    region: '杭州市市辖区',
    name: '云河隧道',
    type: '城市道路隧道',
    cityClassification: '中隧道',
    buildTime: '2018-05-25',
    isUnderground: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-05',
    isOverdue: '未超期',
    status: '在用',
    liningType: '复合式衬砌',
    hasMultiUnit: false,
    industryUnit: '杭州市交通运输局',
    industryPerson: '张明',
    industryContact: '0571-88000001',
    facilityManageUnit: '杭州市市政设施管理中心',
    facilityManagePerson: '李强',
    facilityManageContact: '0571-88000002',
    facilityMaintainUnit: '杭州市隧道养护公司',
    facilityMaintainPerson: '王勇',
    facilityMaintainContact: '0571-88000003',
    policeUnit: '杭州市交警支队',
    policeContact: '赵刚',
    policeContactPhone: '0571-88000004',
    tunnelLocation: '杭州市西湖区云河路段',
    cardData: {
      name: '云河隧道',
      roadName: '云河路',
      district: '杭州市市辖区',
      manageUnit: '杭州市市政设施管理中心',
      maintainUnit: '杭州市隧道养护公司',
      crossOver: '路',
      buildDate: '2018-05-25',
      buildUnit: '中铁隧道工程局集团',
      totalCost: '825000',
      surveyUnit: '浙江省交通勘察设计院',
      maintainCategory: '一类',
      designUnit: '浙江省交通规划设计研究院',
      maintainGrade: '一级',
      superviseUnit: '浙江工程建设监理公司',
      roadGrade: '主干路',
      constructUnit: '中铁隧道工程局集团',
      designLanes: '双向四车道',
      designLoad: '公路-I级',
      designSpeed: '60',
      designFlow: '2400',
      emergencyPhone: '有',
      roadCrossSection: '2.5+3.5+3.5+2.5',
      motorPavement: '沥青混凝土',
      nonMotorPavement: '沥青混凝土',
      sidewalkPavement: '预制砖',
      drivewayLengthSingle: '550',
      drivewayWidth: '10.5',
      drivewayLength: '550',
      sidewalkWidth: '1.0',
      motorMaxSlope: '1.5%',
      nonMotorMaxSlope: '1.2%',
      crossSlope: '1.5%',
      waterproofGrade: '二级',
      geology: 'IV级围岩',
      liningType: '复合式衬砌',
      liningThickness: '45',
      portalForm: '削竹式',
      ceilingDecoration: '铝板',
      ceilingDecorationArea: '5500',
      wallDecoration: '瓷砖',
      wallDecorationArea: '4400',
      crashWallDecoration: '涂料',
      crashWallDecorationArea: '1100',
      motorClearHeight: '4.5',
      nonMotorClearHeight: '2.5',
      designFloodLevel: '8.5',
      sewagePumpCount: '1',
      rainPumpCount: '2',
      railingForm: '钢栏杆',
      railingLength: '550',
      drainForm: '明沟',
      drainLength: '550',
      topDrainForm: '截水沟',
      overview: '云河隧道位于杭州市市辖区，全长550米，2018-05-25建成通车。',
      review: '张工',
      check: '李工',
      drafting: '王工',
      cardDate: '2026-07-05',
    },
    detectRecords: [
      { id: 1, name: '定期检查', checkTime: '2026-07-05', type: 'A', grade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-07-01', type: 'A', grade: 'A', result: '' },
    ],

  },
  {
    key: '7',
    region: '金华市金华开发区',
    name: '双龙南街地下通道',
    type: '人行地道',
    cityClassification: '—',
    buildTime: '2021-02-18',
    isUnderground: true,
    hasMonitorDevice: true,
    hasMonitorFacility: false,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-06-18',
    isOverdue: '未超期',
    status: '在用',
    liningType: '复合式衬砌',
    hasMultiUnit: false,
    industryUnit: '金华开发区交通分局',
    industryPerson: '谭明',
    industryContact: '0579-2300001',
    facilityManageUnit: '金华开发区市政管理处',
    facilityManagePerson: '卢勇',
    facilityManageContact: '0579-2300002',
    facilityMaintainUnit: '金华开发区道路养护中心',
    facilityMaintainPerson: '莫凡',
    facilityMaintainContact: '0579-2300003',
    policeUnit: '金华开发区交警大队',
    policeContact: '童欣',
    policeContactPhone: '0579-2300004',
    tunnelLocation: '金华市双龙南街地下通道',
    underpassCard: {
      name: '双龙南街地下通道',
      roadName: '双龙南街路',
      crossOver: '路',
      manageUnit: '金华开发区市政管理处',
      buildUnit: '市政工程建设公司',
      designUnit: '浙江省交通规划设计研究院',
      supervisorUnit: '工程监理咨询公司',
      constructionUnit: '城建工程公司',
      buildDate: '2021-02-18',
      totalLength: '45',
      passageWidth: '6',
      height: '3.5',
      liningStructure: '钢筋混凝土箱涵',
      sidewalkPavement: '防滑瓷砖',
      expansionJointType: '型钢伸缩缝',
      roadCrossSlope: '1.0%',
      lightingName: 'LED地道灯',
      lightingCount: '18',
      powerName: '配电箱',
      powerCount: '2',
      drainageName: '集水井+排水泵',
      drainageCount: '2',
      ventilationName: '射流风机',
      ventilationCount: '4',
      fireFightingName: '干粉灭火器',
      fireFightingCount: '8',
      elevatorBrand: '上海三菱',
      elevatorCount: '2',
      audit: '陈明',
      review: '张工',
      draft: '王工',
      cardDate: '2026-06-18',
    },
    detectRecords: [
      { id: 1, name: '定期检查', checkTime: '2026-06-18', type: 'A', grade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-06-01', type: 'A', grade: 'A', result: '' },
    ],

  },
  {
    key: '8',
    region: '杭州市市辖区',
    name: '九沙大道1#人行过街地道',
    type: '人行地道',
    cityClassification: '—',
    buildTime: '2019-10-30',
    isUnderground: true,
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: 'B',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-03-10',
    isOverdue: '未超期',
    status: '在用',
    liningType: '复合式衬砌',
    hasMultiUnit: false,
    industryUnit: '杭州市交通运输局',
    industryPerson: '张明',
    industryContact: '0571-88000001',
    facilityManageUnit: '杭州市市政设施管理中心',
    facilityManagePerson: '李强',
    facilityManageContact: '0571-88000002',
    facilityMaintainUnit: '杭州市隧道养护公司',
    facilityMaintainPerson: '王勇',
    facilityMaintainContact: '0571-88000003',
    policeUnit: '杭州市交警支队',
    policeContact: '赵刚',
    policeContactPhone: '0571-88000004',
    tunnelLocation: '杭州市江干区九沙大道',
    underpassCard: {
      name: '九沙大道1#人行过街地道',
      roadName: '九沙大道1#路',
      crossOver: '路',
      manageUnit: '杭州市市政设施管理中心',
      buildUnit: '市政工程建设公司',
      designUnit: '浙江省交通规划设计研究院',
      supervisorUnit: '工程监理咨询公司',
      constructionUnit: '城建工程公司',
      buildDate: '2019-10-30',
      totalLength: '52',
      passageWidth: '5',
      height: '3.2',
      liningStructure: '钢筋混凝土箱涵',
      sidewalkPavement: '防滑瓷砖',
      expansionJointType: '型钢伸缩缝',
      roadCrossSlope: '1.0%',
      lightingName: 'LED地道灯',
      lightingCount: '18',
      powerName: '配电箱',
      powerCount: '2',
      drainageName: '集水井+排水泵',
      drainageCount: '2',
      ventilationName: '射流风机',
      ventilationCount: '4',
      fireFightingName: '干粉灭火器',
      fireFightingCount: '8',
      elevatorBrand: '上海三菱',
      elevatorCount: '2',
      audit: '陈明',
      review: '张工',
      draft: '王工',
      cardDate: '2026-03-10',
    },
    detectRecords: [
      { id: 1, name: '定期检查', checkTime: '2026-03-10', type: 'A', grade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-03-01', type: 'A', grade: 'A', result: '' },
    ],

  },
  {
    key: '9',
    region: '杭州市萧山区',
    name: '湘湖浅埋隧道（下穿）',
    type: '城市道路隧道',
    cityClassification: '短隧道',
    buildTime: '2020-06-15',
    isUnderground: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-22',
    isOverdue: '未超期',
    status: '在用',
    liningType: '复合式衬砌',
    hasMultiUnit: false,
    industryUnit: '杭州市交通运输局',
    industryPerson: '张明',
    industryContact: '0571-88000001',
    facilityManageUnit: '萧山区市政设施管理所',
    facilityManagePerson: '韩雪',
    facilityManageContact: '0571-83800002',
    facilityMaintainUnit: '萧山区道路养护中心',
    facilityMaintainPerson: '杨光',
    facilityMaintainContact: '0571-83800003',
    policeUnit: '萧山区交警大队',
    policeContact: '秦刚',
    policeContactPhone: '0571-83800004',
    tunnelLocation: '杭州市萧山区湘湖景区下穿段',
    cardData: {
      name: '湘湖浅埋隧道（下穿）',
      roadName: '湘湖浅埋路（路）',
      district: '杭州市萧山区',
      manageUnit: '萧山区市政设施管理所',
      maintainUnit: '萧山区道路养护中心',
      crossOver: '路',
      buildDate: '2020-06-15',
      buildUnit: '中铁隧道工程局集团',
      totalCost: '420000',
      surveyUnit: '浙江省交通勘察设计院',
      maintainCategory: '一类',
      designUnit: '浙江省交通规划设计研究院',
      maintainGrade: '一级',
      superviseUnit: '浙江工程建设监理公司',
      roadGrade: '次干路',
      constructUnit: '中铁隧道工程局集团',
      designLanes: '双向四车道',
      designLoad: '公路-I级',
      designSpeed: '50',
      designFlow: '1800',
      emergencyPhone: '有',
      roadCrossSection: '2.5+3.5+3.5+2.5',
      motorPavement: '沥青混凝土',
      nonMotorPavement: '沥青混凝土',
      sidewalkPavement: '预制砖',
      drivewayLengthSingle: '280',
      drivewayWidth: '8.0',
      drivewayLength: '280',
      sidewalkWidth: '1.0',
      motorMaxSlope: '1.5%',
      nonMotorMaxSlope: '1.2%',
      crossSlope: '1.5%',
      waterproofGrade: '二级',
      geology: 'IV级围岩',
      liningType: '复合式衬砌',
      liningThickness: '45',
      portalForm: '削竹式',
      ceilingDecoration: '铝板',
      ceilingDecorationArea: '2800',
      wallDecoration: '瓷砖',
      wallDecorationArea: '2240',
      crashWallDecoration: '涂料',
      crashWallDecorationArea: '560',
      motorClearHeight: '4.5',
      nonMotorClearHeight: '2.5',
      designFloodLevel: '8.5',
      sewagePumpCount: '1',
      rainPumpCount: '2',
      railingForm: '钢栏杆',
      railingLength: '280',
      drainForm: '明沟',
      drainLength: '280',
      topDrainForm: '截水沟',
      overview: '湘湖浅埋隧道（下穿）位于杭州市萧山区，全长280米，2020-06-15建成通车。',
      review: '张工',
      check: '李工',
      drafting: '王工',
      cardDate: '2026-07-22',
    },
    detectRecords: [
      { id: 1, name: '定期检查', checkTime: '2026-07-22', type: 'A', grade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-07-01', type: 'A', grade: 'A', result: '' },
    ],

  },
  {
    key: '10',
    region: '宁波市镇海区',
    name: '招宝山隧道',
    type: '城市道路隧道',
    cityClassification: '特长隧道',
    buildTime: '2013-08-20',
    isUnderground: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-06-30',
    isOverdue: '未超期',
    status: '在用',
    liningType: '复合式衬砌',
    hasMultiUnit: true,
    industryUnit: '镇海区交通运输局',
    industryPerson: '孙磊',
    industryContact: '0574-86200001',
    facilityManageUnit: '镇海区市政设施管理所',
    facilityManagePerson: '钱波',
    facilityManageContact: '0574-86200002',
    facilityMaintainUnit: '镇海区道路养护中心',
    facilityMaintainPerson: '冯涛',
    facilityMaintainContact: '0574-86200003',
    policeUnit: '镇海区交警大队',
    policeContact: '蒋华',
    policeContactPhone: '0574-86200004',
    tunnelLocation: '镇海区招宝山段',
    tunnelUnits: [
      {
        name: '招宝山隧道（单元1）',
        roadName: '招宝山路',
        district: '宁波市镇海区',
        manageUnit: '镇海区市政设施管理所',
        maintainUnit: '镇海区道路养护中心',
        crossOver: '路',
        buildDate: '2013-08-20',
        buildUnit: '中铁隧道工程局集团',
        totalCost: '3150000',
        surveyUnit: '浙江省交通勘察设计院',
        maintainCategory: '一类',
        designUnit: '浙江省交通规划设计研究院',
        maintainGrade: '一级',
        superviseUnit: '浙江工程建设监理公司',
        roadGrade: '快速路',
        constructUnit: '中铁隧道工程局集团',
        designLanes: '双向六车道',
        designLoad: '公路-I级',
        designSpeed: '80',
        designFlow: '3600',
        emergencyPhone: '有',
        roadCrossSection: '2.5+3.75+3.75+3.75+3.75+2.5',
        motorPavement: '沥青混凝土',
        nonMotorPavement: '沥青混凝土',
        sidewalkPavement: '预制砖',
        drivewayLengthSingle: '1050',
        drivewayWidth: '15.5',
        drivewayLength: '1050',
        sidewalkWidth: '1.0',
        motorMaxSlope: '1.5%',
        nonMotorMaxSlope: '1.2%',
        crossSlope: '1.5%',
        waterproofGrade: '二级',
        geology: 'IV级围岩',
        liningType: '复合式衬砌',
        liningThickness: '45',
        portalForm: '削竹式',
        ceilingDecoration: '铝板',
        ceilingDecorationArea: '10500',
        wallDecoration: '瓷砖',
        wallDecorationArea: '8400',
        crashWallDecoration: '涂料',
        crashWallDecorationArea: '2100',
        motorClearHeight: '4.5',
        nonMotorClearHeight: '2.5',
        designFloodLevel: '8.5',
        sewagePumpCount: '1',
        rainPumpCount: '2',
        railingForm: '钢栏杆',
        railingLength: '1050',
        drainForm: '明沟',
        drainLength: '1050',
        topDrainForm: '截水沟',
        overview: '招宝山隧道单元1，全长1050米，2013-08-20建成通车。',
        review: '张工',
        check: '李工',
        drafting: '王工',
        cardDate: '2026-06-30',
      },
      {
        name: '招宝山隧道（单元2）',
        roadName: '招宝山路',
        district: '宁波市镇海区',
        manageUnit: '镇海区市政设施管理所',
        maintainUnit: '镇海区道路养护中心',
        crossOver: '路',
        buildDate: '2013-08-20',
        buildUnit: '中铁隧道工程局集团',
        totalCost: '3150000',
        surveyUnit: '浙江省交通勘察设计院',
        maintainCategory: '一类',
        designUnit: '浙江省交通规划设计研究院',
        maintainGrade: '一级',
        superviseUnit: '浙江工程建设监理公司',
        roadGrade: '快速路',
        constructUnit: '中铁隧道工程局集团',
        designLanes: '双向六车道',
        designLoad: '公路-I级',
        designSpeed: '80',
        designFlow: '3600',
        emergencyPhone: '有',
        roadCrossSection: '2.5+3.75+3.75+3.75+3.75+2.5',
        motorPavement: '沥青混凝土',
        nonMotorPavement: '沥青混凝土',
        sidewalkPavement: '预制砖',
        drivewayLengthSingle: '1050',
        drivewayWidth: '15.5',
        drivewayLength: '1050',
        sidewalkWidth: '1.0',
        motorMaxSlope: '1.5%',
        nonMotorMaxSlope: '1.2%',
        crossSlope: '1.5%',
        waterproofGrade: '二级',
        geology: 'IV级围岩',
        liningType: '复合式衬砌',
        liningThickness: '45',
        portalForm: '削竹式',
        ceilingDecoration: '铝板',
        ceilingDecorationArea: '10500',
        wallDecoration: '瓷砖',
        wallDecorationArea: '8400',
        crashWallDecoration: '涂料',
        crashWallDecorationArea: '2100',
        motorClearHeight: '4.5',
        nonMotorClearHeight: '2.5',
        designFloodLevel: '8.5',
        sewagePumpCount: '1',
        rainPumpCount: '2',
        railingForm: '钢栏杆',
        railingLength: '1050',
        drainForm: '明沟',
        drainLength: '1050',
        topDrainForm: '截水沟',
        overview: '招宝山隧道单元2，全长1050米，2013-08-20建成通车。',
        review: '陈工',
        check: '赵工',
        drafting: '孙工',
        cardDate: '2026-06-30',
      },
    ],
    detectRecords: [
      { id: 1, name: '定期检查', checkTime: '2026-06-30', type: 'A', grade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-06-01', type: 'A', grade: 'A', result: '' },
    ],

  },
  {
    key: '11',
    region: '温州市平阳县',
    name: '鳌江隧道',
    type: '城市道路隧道',
    cityClassification: '中隧道',
    buildTime: '2016-12-10',
    isUnderground: true,
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: 'C',
    evalYear: 2023,
    dataComplete: false,
    publishStatus: '草稿',
    detectTime: '2025-11-08',
    isOverdue: '已超期',
    status: '在用',
    liningType: '复合式衬砌',
    hasMultiUnit: false,
    industryUnit: '平阳县交通运输局',
    industryPerson: '苏晨',
    industryContact: '0577-6310001',
    facilityManageUnit: '平阳县市政管理处',
    facilityManagePerson: '黄磊',
    facilityManageContact: '0577-6310002',
    facilityMaintainUnit: '平阳县公路养护段',
    facilityMaintainPerson: '曹颖',
    facilityMaintainContact: '0577-6310003',
    policeUnit: '平阳县交警大队',
    policeContact: '薛军',
    policeContactPhone: '0577-6310004',
    tunnelLocation: '平阳县鳌江镇段',
    cardData: {
      name: '鳌江隧道',
      roadName: '鳌江路',
      district: '温州市平阳县',
      manageUnit: '平阳县市政管理处',
      maintainUnit: '平阳县公路养护段',
      crossOver: '路',
      buildDate: '2016-12-10',
      buildUnit: '中铁隧道工程局集团',
      totalCost: '1080000',
      surveyUnit: '浙江省交通勘察设计院',
      maintainCategory: '一类',
      designUnit: '浙江省交通规划设计研究院',
      maintainGrade: '一级',
      superviseUnit: '浙江工程建设监理公司',
      roadGrade: '主干路',
      constructUnit: '中铁隧道工程局集团',
      designLanes: '双向四车道',
      designLoad: '公路-I级',
      designSpeed: '60',
      designFlow: '2400',
      emergencyPhone: '有',
      roadCrossSection: '2.5+3.5+3.5+2.5',
      motorPavement: '沥青混凝土',
      nonMotorPavement: '沥青混凝土',
      sidewalkPavement: '预制砖',
      drivewayLengthSingle: '720',
      drivewayWidth: '10.5',
      drivewayLength: '720',
      sidewalkWidth: '1.0',
      motorMaxSlope: '1.5%',
      nonMotorMaxSlope: '1.2%',
      crossSlope: '1.5%',
      waterproofGrade: '二级',
      geology: 'IV级围岩',
      liningType: '复合式衬砌',
      liningThickness: '45',
      portalForm: '削竹式',
      ceilingDecoration: '铝板',
      ceilingDecorationArea: '7200',
      wallDecoration: '瓷砖',
      wallDecorationArea: '5760',
      crashWallDecoration: '涂料',
      crashWallDecorationArea: '1440',
      motorClearHeight: '4.5',
      nonMotorClearHeight: '2.5',
      designFloodLevel: '8.5',
      sewagePumpCount: '1',
      rainPumpCount: '2',
      railingForm: '钢栏杆',
      railingLength: '720',
      drainForm: '明沟',
      drainLength: '720',
      topDrainForm: '截水沟',
      overview: '鳌江隧道位于温州市平阳县，全长720米，2016-12-10建成通车。',
      review: '张工',
      check: '李工',
      drafting: '王工',
      cardDate: '2025-11-08',
    },
    detectRecords: [
      { id: 1, name: '定期检查', checkTime: '2025-11-08', type: 'C', grade: 'C', result: '' },
      { id: 2, name: '经常检查', checkTime: '2025-11-01', type: 'C', grade: 'C', result: '' },
    ],

  },
  {
    key: '12',
    region: '绍兴市柯桥区',
    name: '柯岩隧道',
    type: '城市道路隧道',
    cityClassification: '长隧道',
    buildTime: '2018-04-15',
    isUnderground: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-05-28',
    isOverdue: '未超期',
    status: '在建',
    liningType: '复合式衬砌',
    hasMultiUnit: true,
    industryUnit: '柯桥区交通运输局',
    industryPerson: '高峰',
    industryContact: '0575-84100001',
    facilityManageUnit: '柯桥区市政设施管理所',
    facilityManagePerson: '唐杰',
    facilityManageContact: '0575-84100002',
    facilityMaintainUnit: '柯桥区道路养护公司',
    facilityMaintainPerson: '邓超',
    facilityMaintainContact: '0575-84100003',
    policeUnit: '柯桥区交警大队',
    policeContact: '曾鸣',
    policeContactPhone: '0575-84100004',
    tunnelLocation: '柯桥区柯岩段',
    tunnelUnits: [
      {
        name: '柯岩隧道（单元1）',
        roadName: '柯岩路',
        district: '绍兴市柯桥区',
        manageUnit: '柯桥区市政设施管理所',
        maintainUnit: '柯桥区道路养护公司',
        crossOver: '路',
        buildDate: '2018-04-15',
        buildUnit: '中铁隧道工程局集团',
        totalCost: '2175000',
        surveyUnit: '浙江省交通勘察设计院',
        maintainCategory: '一类',
        designUnit: '浙江省交通规划设计研究院',
        maintainGrade: '一级',
        superviseUnit: '浙江工程建设监理公司',
        roadGrade: '快速路',
        constructUnit: '中铁隧道工程局集团',
        designLanes: '双向六车道',
        designLoad: '公路-I级',
        designSpeed: '80',
        designFlow: '3600',
        emergencyPhone: '有',
        roadCrossSection: '2.5+3.75+3.75+3.75+3.75+2.5',
        motorPavement: '沥青混凝土',
        nonMotorPavement: '沥青混凝土',
        sidewalkPavement: '预制砖',
        drivewayLengthSingle: '725',
        drivewayWidth: '15.5',
        drivewayLength: '725',
        sidewalkWidth: '1.0',
        motorMaxSlope: '1.5%',
        nonMotorMaxSlope: '1.2%',
        crossSlope: '1.5%',
        waterproofGrade: '二级',
        geology: 'IV级围岩',
        liningType: '复合式衬砌',
        liningThickness: '45',
        portalForm: '削竹式',
        ceilingDecoration: '铝板',
        ceilingDecorationArea: '7250',
        wallDecoration: '瓷砖',
        wallDecorationArea: '5800',
        crashWallDecoration: '涂料',
        crashWallDecorationArea: '1450',
        motorClearHeight: '4.5',
        nonMotorClearHeight: '2.5',
        designFloodLevel: '8.5',
        sewagePumpCount: '1',
        rainPumpCount: '2',
        railingForm: '钢栏杆',
        railingLength: '725',
        drainForm: '明沟',
        drainLength: '725',
        topDrainForm: '截水沟',
        overview: '柯岩隧道单元1，全长725米，2018-04-15建成通车。',
        review: '张工',
        check: '李工',
        drafting: '王工',
        cardDate: '2026-05-28',
      },
      {
        name: '柯岩隧道（单元2）',
        roadName: '柯岩路',
        district: '绍兴市柯桥区',
        manageUnit: '柯桥区市政设施管理所',
        maintainUnit: '柯桥区道路养护公司',
        crossOver: '路',
        buildDate: '2018-04-15',
        buildUnit: '中铁隧道工程局集团',
        totalCost: '2175000',
        surveyUnit: '浙江省交通勘察设计院',
        maintainCategory: '一类',
        designUnit: '浙江省交通规划设计研究院',
        maintainGrade: '一级',
        superviseUnit: '浙江工程建设监理公司',
        roadGrade: '快速路',
        constructUnit: '中铁隧道工程局集团',
        designLanes: '双向六车道',
        designLoad: '公路-I级',
        designSpeed: '80',
        designFlow: '3600',
        emergencyPhone: '有',
        roadCrossSection: '2.5+3.75+3.75+3.75+3.75+2.5',
        motorPavement: '沥青混凝土',
        nonMotorPavement: '沥青混凝土',
        sidewalkPavement: '预制砖',
        drivewayLengthSingle: '725',
        drivewayWidth: '15.5',
        drivewayLength: '725',
        sidewalkWidth: '1.0',
        motorMaxSlope: '1.5%',
        nonMotorMaxSlope: '1.2%',
        crossSlope: '1.5%',
        waterproofGrade: '二级',
        geology: 'IV级围岩',
        liningType: '复合式衬砌',
        liningThickness: '45',
        portalForm: '削竹式',
        ceilingDecoration: '铝板',
        ceilingDecorationArea: '7250',
        wallDecoration: '瓷砖',
        wallDecorationArea: '5800',
        crashWallDecoration: '涂料',
        crashWallDecorationArea: '1450',
        motorClearHeight: '4.5',
        nonMotorClearHeight: '2.5',
        designFloodLevel: '8.5',
        sewagePumpCount: '1',
        rainPumpCount: '2',
        railingForm: '钢栏杆',
        railingLength: '725',
        drainForm: '明沟',
        drainLength: '725',
        topDrainForm: '截水沟',
        overview: '柯岩隧道单元2，全长725米，2018-04-15建成通车。',
        review: '陈工',
        check: '赵工',
        drafting: '孙工',
        cardDate: '2026-05-28',
      },
    ],
    detectRecords: [
      { id: 1, name: '定期检查', checkTime: '2026-05-28', type: 'A', grade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-05-01', type: 'A', grade: 'A', result: '' },
    ],

  },
  {
    key: '13',
    region: '台州市椒江区',
    name: '椒江穿山隧道',
    type: '城市道路隧道',
    cityClassification: '长隧道',
    buildTime: '2017-09-22',
    isUnderground: true,
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'B',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-04-12',
    isOverdue: '未超期',
    status: '在用',
    liningType: '复合式衬砌',
    hasMultiUnit: true,
    industryUnit: '椒江区交通运输局',
    industryPerson: '毛勇',
    industryContact: '0576-8880001',
    facilityManageUnit: '椒江区市政设施管理所',
    facilityManagePerson: '段飞',
    facilityManageContact: '0576-8880002',
    facilityMaintainUnit: '椒江区道路养护中心',
    facilityMaintainPerson: '雷鸣',
    facilityMaintainContact: '0576-8880003',
    policeUnit: '椒江区交警大队',
    policeContact: '文斌',
    policeContactPhone: '0576-8880004',
    tunnelLocation: '椒江区穿山段',
    tunnelUnits: [
      {
        name: '椒江穿山隧道（单元1）',
        roadName: '椒江穿山路',
        district: '台州市椒江区',
        manageUnit: '椒江区市政设施管理所',
        maintainUnit: '椒江区道路养护中心',
        crossOver: '路',
        buildDate: '2017-09-22',
        buildUnit: '中铁隧道工程局集团',
        totalCost: '2070000',
        surveyUnit: '浙江省交通勘察设计院',
        maintainCategory: '一类',
        designUnit: '浙江省交通规划设计研究院',
        maintainGrade: '一级',
        superviseUnit: '浙江工程建设监理公司',
        roadGrade: '快速路',
        constructUnit: '中铁隧道工程局集团',
        designLanes: '双向六车道',
        designLoad: '公路-I级',
        designSpeed: '80',
        designFlow: '3600',
        emergencyPhone: '有',
        roadCrossSection: '2.5+3.75+3.75+3.75+3.75+2.5',
        motorPavement: '沥青混凝土',
        nonMotorPavement: '沥青混凝土',
        sidewalkPavement: '预制砖',
        drivewayLengthSingle: '690',
        drivewayWidth: '15.5',
        drivewayLength: '690',
        sidewalkWidth: '1.0',
        motorMaxSlope: '1.5%',
        nonMotorMaxSlope: '1.2%',
        crossSlope: '1.5%',
        waterproofGrade: '二级',
        geology: 'IV级围岩',
        liningType: '复合式衬砌',
        liningThickness: '45',
        portalForm: '削竹式',
        ceilingDecoration: '铝板',
        ceilingDecorationArea: '6900',
        wallDecoration: '瓷砖',
        wallDecorationArea: '5520',
        crashWallDecoration: '涂料',
        crashWallDecorationArea: '1380',
        motorClearHeight: '4.5',
        nonMotorClearHeight: '2.5',
        designFloodLevel: '8.5',
        sewagePumpCount: '1',
        rainPumpCount: '2',
        railingForm: '钢栏杆',
        railingLength: '690',
        drainForm: '明沟',
        drainLength: '690',
        topDrainForm: '截水沟',
        overview: '椒江穿山隧道单元1，全长690米，2017-09-22建成通车。',
        review: '张工',
        check: '李工',
        drafting: '王工',
        cardDate: '2026-04-12',
      },
      {
        name: '椒江穿山隧道（单元2）',
        roadName: '椒江穿山路',
        district: '台州市椒江区',
        manageUnit: '椒江区市政设施管理所',
        maintainUnit: '椒江区道路养护中心',
        crossOver: '路',
        buildDate: '2017-09-22',
        buildUnit: '中铁隧道工程局集团',
        totalCost: '2070000',
        surveyUnit: '浙江省交通勘察设计院',
        maintainCategory: '一类',
        designUnit: '浙江省交通规划设计研究院',
        maintainGrade: '一级',
        superviseUnit: '浙江工程建设监理公司',
        roadGrade: '快速路',
        constructUnit: '中铁隧道工程局集团',
        designLanes: '双向六车道',
        designLoad: '公路-I级',
        designSpeed: '80',
        designFlow: '3600',
        emergencyPhone: '有',
        roadCrossSection: '2.5+3.75+3.75+3.75+3.75+2.5',
        motorPavement: '沥青混凝土',
        nonMotorPavement: '沥青混凝土',
        sidewalkPavement: '预制砖',
        drivewayLengthSingle: '690',
        drivewayWidth: '15.5',
        drivewayLength: '690',
        sidewalkWidth: '1.0',
        motorMaxSlope: '1.5%',
        nonMotorMaxSlope: '1.2%',
        crossSlope: '1.5%',
        waterproofGrade: '二级',
        geology: 'IV级围岩',
        liningType: '复合式衬砌',
        liningThickness: '45',
        portalForm: '削竹式',
        ceilingDecoration: '铝板',
        ceilingDecorationArea: '6900',
        wallDecoration: '瓷砖',
        wallDecorationArea: '5520',
        crashWallDecoration: '涂料',
        crashWallDecorationArea: '1380',
        motorClearHeight: '4.5',
        nonMotorClearHeight: '2.5',
        designFloodLevel: '8.5',
        sewagePumpCount: '1',
        rainPumpCount: '2',
        railingForm: '钢栏杆',
        railingLength: '690',
        drainForm: '明沟',
        drainLength: '690',
        topDrainForm: '截水沟',
        overview: '椒江穿山隧道单元2，全长690米，2017-09-22建成通车。',
        review: '陈工',
        check: '赵工',
        drafting: '孙工',
        cardDate: '2026-04-12',
      },
    ],
    detectRecords: [
      { id: 1, name: '定期检查', checkTime: '2026-04-12', type: 'B', grade: 'B', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-04-01', type: 'B', grade: 'B', result: '' },
    ],

  },
]

// 模拟获取隧道列表
export function getTunnelList(
  params: TunnelSearchParams
): Promise<{ list: TunnelItem[]; total: number; page: number; pageSize: number }> {
  return new Promise((resolve) => {
    setTimeout(() => {
      let filteredList = [...mockTunnels]

      // 筛选
      if (params.region) {
        filteredList = filteredList.filter((item) => item.region.includes(params.region!))
      }
      if (params.name) {
        filteredList = filteredList.filter((item) => item.name.includes(params.name!))
      }
      if (params.type) {
        filteredList = filteredList.filter((item) => item.type === params.type)
      }
      if (params.cityClassification) {
        filteredList = filteredList.filter((item) => item.cityClassification === params.cityClassification)
      }
      if (params.isUnderground) {
        const val = params.isUnderground === '是'
        filteredList = filteredList.filter((item) => item.isUnderground === val)
      }
      if (params.evalLevel) {
        filteredList = filteredList.filter((item) => item.evalLevel === params.evalLevel)
      }
      if (params.status) {
        filteredList = filteredList.filter((item) => item.status === params.status)
      }
      if (params.dataComplete) {
        const val = params.dataComplete === '是'
        filteredList = filteredList.filter((item) => item.dataComplete === val)
      }
      if (params.publishStatus) {
        filteredList = filteredList.filter((item) => item.publishStatus === params.publishStatus)
      }
      if (params.isOverdue) {
        filteredList = filteredList.filter((item) => item.isOverdue === params.isOverdue)
      }

      // 分页
      const total = filteredList.length
      const page = params.page || 1
      const pageSize = params.pageSize || 10
      const start = (page - 1) * pageSize
      const end = start + pageSize
      const list = filteredList.slice(start, end)

      resolve({
        list,
        total,
        page,
        pageSize,
      })
    }, 500)
  })
}

// 归属地区选项 — 浙江省11个地市的区县
export const regionOptions = [
  { label: '杭州市市辖区', value: '杭州市市辖区' },
  { label: '杭州市余杭区', value: '杭州市余杭区' },
  { label: '杭州市拱墅区', value: '杭州市拱墅区' },
  { label: '杭州市西湖区', value: '杭州市西湖区' },
  { label: '杭州市滨江区', value: '杭州市滨江区' },
  { label: '杭州市萧山区', value: '杭州市萧山区' },
  { label: '宁波市市辖区', value: '宁波市市辖区' },
  { label: '宁波市镇海区', value: '宁波市镇海区' },
  { label: '温州市平阳县', value: '温州市平阳县' },
  { label: '嘉兴市南湖区', value: '嘉兴市南湖区' },
  { label: '嘉兴市嘉兴港区', value: '嘉兴市嘉兴港区' },
  { label: '湖州市南太湖新区', value: '湖州市南太湖新区' },
  { label: '湖州市安吉县', value: '湖州市安吉县' },
  { label: '绍兴市柯桥区', value: '绍兴市柯桥区' },
  { label: '金华市兰溪市', value: '金华市兰溪市' },
  { label: '金华市义乌市', value: '金华市义乌市' },
  { label: '丽水市缙云县', value: '丽水市缙云县' },
  { label: '台州市椒江区', value: '台州市椒江区' },
  { label: '衢州市柯城区', value: '衢州市柯城区' },
  { label: '舟山市定海区', value: '舟山市定海区' },
]

// 隧道类型选项 — 对齐导则：城市道路隧道 + 人行地道（分组）
export const tunnelTypeOptions = [
  { label: '城市道路隧道', value: '城市道路隧道', group: '城市道路隧道' },
  { label: '人行地道', value: '人行地道', group: '人行地道' },
]

// 城市道路隧道分类选项
export const cityClassificationOptions = [
  { label: '特长隧道', value: '特长隧道' },
  { label: '长隧道', value: '长隧道' },
  { label: '中隧道', value: '中隧道' },
  { label: '短隧道', value: '短隧道' },
]

// 综合评价等级选项
export const evalLevelOptions = [
  { label: 'A', value: 'A' },
  { label: 'B', value: 'B' },
  { label: 'C', value: 'C' },
  { label: 'D', value: 'D' },
  { label: 'E', value: 'E' },
]

// 是否地下隧道选项
export const isUndergroundOptions = [
  { label: '是', value: '是' },
  { label: '否', value: '否' },
]

// 发布状态选项
export const publishStatusOptions = [
  { label: '草稿', value: '草稿' },
  { label: '已发布', value: '已发布' },
]

// 检测是否超期选项
export const isOverdueOptions = [
  { label: '未超期', value: '未超期' },
  { label: '已超期', value: '已超期' },
]

// 数据是否完善选项
export const dataCompleteOptions = [
  { label: '是', value: '是' },
  { label: '否', value: '否' },
]

// 状态选项
export const statusOptions = [
  { label: '在用', value: '在用' },
  { label: '在建', value: '在建' },
  { label: '停用', value: '停用' },
]
