import type { RoadItem, RoadSearchParams } from '@/types/road'

// Mock道路数据 — 使用线上系统真实地名
const mockRoads: RoadItem[] = [
  {
    key: '1',
    region: '杭州市余杭区',
    name: '测试道路-同顺街',
    level: '次干路',
    buildTime: '2015-06-01',
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-08-05',
    isOverdue: '未超期',
    status: '在用',
    // 三级责任体系（对齐线上）
    industryUnit: '浙江省-省政府机构-省建设厅-城市建设处',
    industryPerson: '王雨晴',
    industryContact: '17360312375',
    facilityManageUnit: '浙江省-省政府机构-省建设厅-城市建设处',
    facilityManagePerson: '王雨晴',
    facilityManageContact: '17360312375',
    facilityMaintainUnit: '林木养护公司',
    facilityMaintainPerson: '李四',
    facilityMaintainContact: '18419970005',
    policeUnit: '余杭区公安分局交警大队',
    policeContact: '张慧超',
    policeContactPhone: '13777374512',
    roadLocation: 'MULTILINESTRING((120.0721 30.2332,120.0815 30.2418,120.0897 30.2512))',
    // 检测整改记录（对齐线上）
    detectRecords: [
      { id: 1, name: '测试', checkTime: '2026-08-05', type: '常规检测', evalGrade: 'A', result: '' },
      { id: 2, name: '测试名称', checkTime: '2026-06-22', type: '常规检测', evalGrade: 'B', result: '' },
    ],
  },
  {
    key: '2',
    region: '丽水市缙云县',
    name: '缙云县大桥北路三里灯具市场段道路拓宽改造工程',
    level: '主干路',
    buildTime: '2018-09-15',
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'B',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-20',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '缙云县交通运输局',
    industryPerson: '陈杰',
    industryContact: '0578-3120001',
    facilityManageUnit: '缙云县市政管理处',
    facilityManagePerson: '刘伟',
    facilityManageContact: '0578-3120002',
    facilityMaintainUnit: '缙云县公路养护段',
    facilityMaintainPerson: '周涛',
    facilityMaintainContact: '0578-3120003',
    policeUnit: '缙云县交警大队',
    policeContact: '吴敏',
    policeContactPhone: '0578-3120004',
    roadLocation: '缙云县大桥北路三里灯具市场段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-07-20', type: '常规检测', evalGrade: 'B', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-07-01', type: '经常检查', evalGrade: 'B', result: '' },
    ],

  },
  {
    key: '3',
    region: '宁波市镇海区',
    name: '骆驼街道马家桥及三五路（马家桥至南一路段）改造工程',
    level: '支路',
    buildTime: '2020-03-10',
    hasMonitorDevice: true,
    hasMonitorFacility: false,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-06-15',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '镇海区交通运输局',
    industryPerson: '孙磊',
    industryContact: '0574-86200001',
    facilityManageUnit: '镇海区市政设施管理所',
    facilityManagePerson: '钱波',
    facilityManageContact: '0574-86200002',
    facilityMaintainUnit: '镇海区道路养护中心',
    facilityMaintainPerson: '冯涛',
    facilityMaintainContact: '0574-86200003',
    policeUnit: '镇海区交警大队',
    policeContact: '蒋华',
    policeContactPhone: '0574-86200004',
    roadLocation: '镇海区骆驼街道马家桥至南一路段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-06-15', type: '常规检测', evalGrade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-06-01', type: '经常检查', evalGrade: 'A', result: '' },
    ],

  },
  {
    key: '4',
    region: '杭州市拱墅区',
    name: '运河新城一号支路（金昌路-谢村路）',
    level: '支路',
    buildTime: '2019-12-20',
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: 'B',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-05-10',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '拱墅区交通运输局',
    industryPerson: '韩雪',
    industryContact: '0571-88300001',
    facilityManageUnit: '拱墅区市政设施管理中心',
    facilityManagePerson: '杨光',
    facilityManageContact: '0571-88300002',
    facilityMaintainUnit: '拱墅区道路养护公司',
    facilityMaintainPerson: '朱琳',
    facilityMaintainContact: '0571-88300003',
    policeUnit: '拱墅区交警大队',
    policeContact: '秦刚',
    policeContactPhone: '0571-88300004',
    roadLocation: '拱墅区金昌路至谢村路段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-05-10', type: '常规检测', evalGrade: 'B', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-05-01', type: '经常检查', evalGrade: 'B', result: '' },
    ],

  },
  {
    key: '5',
    region: '嘉兴市嘉兴港区',
    name: '嘉兴电厂一号进场路改造提升工程',
    level: '支路',
    buildTime: '2017-08-01',
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'C',
    evalYear: 2023,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-04-18',
    isOverdue: '已超期',
    status: '在用',
    industryUnit: '嘉兴港区交通运输局',
    industryPerson: '尤勇',
    industryContact: '0573-85500001',
    facilityManageUnit: '嘉兴港区市政管理处',
    facilityManagePerson: '许峰',
    facilityManageContact: '0573-85500002',
    facilityMaintainUnit: '嘉兴港区道路养护中心',
    facilityMaintainPerson: '何明',
    facilityMaintainContact: '0573-85500003',
    policeUnit: '嘉兴港区交警大队',
    policeContact: '罗辉',
    policeContactPhone: '0573-85500004',
    roadLocation: '嘉兴港区电厂一号进场路全段',
    detectRecords: [
      { id: 1, name: '定期检测', checkTime: '2026-04-18', type: '定期检测', evalGrade: 'C', result: '已整改销号' },
      { id: 2, name: '经常检查', checkTime: '2026-04-01', type: '经常检查', evalGrade: 'C', result: '' },
    ],

  },
  {
    key: '6',
    region: '绍兴市柯桥区',
    name: '创意路及怡华北路段整治提升工程',
    level: '主干路',
    buildTime: '2016-05-12',
    hasMonitorDevice: true,
    hasMonitorFacility: false,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-05',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '柯桥区交通运输局',
    industryPerson: '高峰',
    industryContact: '0575-84100001',
    facilityManageUnit: '柯桥区市政设施管理所',
    facilityManagePerson: '唐杰',
    facilityManageContact: '0575-84100002',
    facilityMaintainUnit: '柯桥区道路养护公司',
    facilityMaintainPerson: '邓超',
    facilityMaintainContact: '0575-84100003',
    policeUnit: '柯桥区交警大队',
    policeContact: '曾鸣',
    policeContactPhone: '0575-84100004',
    roadLocation: '柯桥区创意路及怡华北路段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-07-05', type: '常规检测', evalGrade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-07-01', type: '经常检查', evalGrade: 'A', result: '' },
    ],

  },
  {
    key: '7',
    region: '湖州市南太湖新区',
    name: '宿渎港路',
    level: '主干路',
    buildTime: '2021-02-28',
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-06-30',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '南太湖新区交通分局',
    industryPerson: '彭飞',
    industryContact: '0572-2100001',
    facilityManageUnit: '南太湖新区市政管理处',
    facilityManagePerson: '蔡伟',
    facilityManageContact: '0572-2100002',
    facilityMaintainUnit: '南太湖新区道路养护中心',
    facilityMaintainPerson: '沈健',
    facilityMaintainContact: '0572-2100003',
    policeUnit: '南太湖新区交警大队',
    policeContact: '范斌',
    policeContactPhone: '0572-2100004',
    roadLocation: '湖州市南太湖新区宿渎港路全段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-06-30', type: '常规检测', evalGrade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-06-01', type: '经常检查', evalGrade: 'A', result: '' },
    ],

  },
  {
    key: '8',
    region: '湖州市南太湖新区',
    name: '大船湾路',
    level: '主干路',
    buildTime: '2020-11-15',
    hasMonitorDevice: true,
    hasMonitorFacility: false,
    evalLevel: 'B',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-03-22',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '南太湖新区交通分局',
    industryPerson: '彭飞',
    industryContact: '0572-2100001',
    facilityManageUnit: '南太湖新区市政管理处',
    facilityManagePerson: '蔡伟',
    facilityManageContact: '0572-2100002',
    facilityMaintainUnit: '南太湖新区道路养护中心',
    facilityMaintainPerson: '沈健',
    facilityMaintainContact: '0572-2100003',
    policeUnit: '南太湖新区交警大队',
    policeContact: '范斌',
    policeContactPhone: '0572-2100004',
    roadLocation: '湖州市南太湖新区大船湾路全段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-03-22', type: '常规检测', evalGrade: 'B', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-03-01', type: '经常检查', evalGrade: 'B', result: '' },
    ],

  },
  {
    key: '9',
    region: '杭州市余杭区',
    name: '文一西路（东西大道-狮山路）',
    level: '快速路',
    buildTime: '2019-07-01',
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-08-01',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '杭州市余杭区交通运输局',
    industryPerson: '张明',
    industryContact: '0571-88500001',
    facilityManageUnit: '余杭区市政设施管理中心',
    facilityManagePerson: '李强',
    facilityManageContact: '0571-88500002',
    facilityMaintainUnit: '余杭区道路养护公司',
    facilityMaintainPerson: '王勇',
    facilityMaintainContact: '0571-88500003',
    policeUnit: '余杭区交警大队',
    policeContact: '赵刚',
    policeContactPhone: '0571-88500004',
    roadLocation: '余杭区文一西路东西大道至狮山路段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-08-01', type: '常规检测', evalGrade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-08-01', type: '经常检查', evalGrade: 'A', result: '' },
    ],

  },
  {
    key: '10',
    region: '杭州市西湖区',
    name: '西溪路（紫金港路-天目山路）提升改造工程',
    level: '次干路',
    buildTime: '2018-10-20',
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: 'B',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '草稿',
    detectTime: '2026-02-15',
    isOverdue: '已超期',
    status: '在用',
    industryUnit: '西湖区交通运输局',
    industryPerson: '林峰',
    industryContact: '0571-87900001',
    facilityManageUnit: '西湖区市政设施管理所',
    facilityManagePerson: '吴昊',
    facilityManageContact: '0571-87900002',
    facilityMaintainUnit: '西湖区道路养护中心',
    facilityMaintainPerson: '郑伟',
    facilityMaintainContact: '0571-87900003',
    policeUnit: '西湖区交警大队',
    policeContact: '刘洋',
    policeContactPhone: '0571-87900004',
    roadLocation: '西湖区西溪路紫金港路至天目山路段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-02-15', type: '常规检测', evalGrade: 'B', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-02-01', type: '经常检查', evalGrade: 'B', result: '' },
    ],

  },
  {
    key: '11',
    region: '宁波市镇海区',
    name: '庄市大道（宁镇路-逸夫路）改造工程',
    level: '主干路',
    buildTime: '2020-06-30',
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-12',
    isOverdue: '未超期',
    status: '在建',
    industryUnit: '镇海区交通运输局',
    industryPerson: '孙磊',
    industryContact: '0574-86200001',
    facilityManageUnit: '镇海区市政设施管理所',
    facilityManagePerson: '钱波',
    facilityManageContact: '0574-86200002',
    facilityMaintainUnit: '镇海区道路养护中心',
    facilityMaintainPerson: '冯涛',
    facilityMaintainContact: '0574-86200003',
    policeUnit: '镇海区交警大队',
    policeContact: '蒋华',
    policeContactPhone: '0574-86200004',
    roadLocation: '镇海区庄市大道宁镇路至逸夫路段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-07-12', type: '常规检测', evalGrade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-07-01', type: '经常检查', evalGrade: 'A', result: '' },
    ],

  },
  {
    key: '12',
    region: '温州市平阳县',
    name: '昆鳌大道（火车站大道-吉祥路）改造工程',
    level: '次干路',
    buildTime: '2017-04-10',
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: 'C',
    evalYear: 2023,
    dataComplete: false,
    publishStatus: '草稿',
    detectTime: '2025-12-10',
    isOverdue: '已超期',
    status: '在用',
    industryUnit: '平阳县交通运输局',
    industryPerson: '苏晨',
    industryContact: '0577-6310001',
    facilityManageUnit: '平阳县市政管理处',
    facilityManagePerson: '黄磊',
    facilityManageContact: '0577-6310002',
    facilityMaintainUnit: '平阳县公路养护段',
    facilityMaintainPerson: '曹颖',
    facilityMaintainContact: '0577-6310003',
    policeUnit: '平阳县交警大队',
    policeContact: '薛军',
    policeContactPhone: '0577-6310004',
    roadLocation: '平阳县昆鳌大道火车站大道至吉祥路段',
    detectRecords: [
      { id: 1, name: '定期检测', checkTime: '2025-12-10', type: '定期检测', evalGrade: 'C', result: '已整改销号' },
      { id: 2, name: '经常检查', checkTime: '2025-12-01', type: '经常检查', evalGrade: 'C', result: '' },
    ],

  },
  {
    key: '13',
    region: '金华市义乌市',
    name: '稠州北路（银海路-诚信大道）整治工程',
    level: '主干路',
    buildTime: '2019-09-25',
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-06-28',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '义乌市交通运输局',
    industryPerson: '胡杰',
    industryContact: '0579-8550001',
    facilityManageUnit: '义乌市市政设施管理中心',
    facilityManagePerson: '余涛',
    facilityManageContact: '0579-8550002',
    facilityMaintainUnit: '义乌市道路养护公司',
    facilityMaintainPerson: '吕波',
    facilityMaintainContact: '0579-8550003',
    policeUnit: '义乌市交警大队',
    policeContact: '施峰',
    policeContactPhone: '0579-8550004',
    roadLocation: '义乌市稠州北路银海路至诚信大道段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-06-28', type: '常规检测', evalGrade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-06-01', type: '经常检查', evalGrade: 'A', result: '' },
    ],

  },
  {
    key: '14',
    region: '台州市椒江区',
    name: '市府大道（机场路-东环大道）拓宽工程',
    level: '快速路',
    buildTime: '2021-01-18',
    hasMonitorDevice: true,
    hasMonitorFacility: false,
    evalLevel: 'B',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-05-25',
    isOverdue: '未超期',
    status: '在建',
    industryUnit: '椒江区交通运输局',
    industryPerson: '毛勇',
    industryContact: '0576-8880001',
    facilityManageUnit: '椒江区市政设施管理所',
    facilityManagePerson: '段飞',
    facilityManageContact: '0576-8880002',
    facilityMaintainUnit: '椒江区道路养护中心',
    facilityMaintainPerson: '雷鸣',
    facilityMaintainContact: '0576-8880003',
    policeUnit: '椒江区交警大队',
    policeContact: '文斌',
    policeContactPhone: '0576-8880004',
    roadLocation: '椒江区市府大道机场路至东环大道段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-05-25', type: '常规检测', evalGrade: 'B', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-05-01', type: '经常检查', evalGrade: 'B', result: '' },
    ],

  },
  {
    key: '15',
    region: '衢州市柯城区',
    name: '府东街（衢江路-荷花路）改造提升工程',
    level: '次干路',
    buildTime: '2016-12-08',
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: 'D',
    evalYear: 2022,
    dataComplete: false,
    publishStatus: '草稿',
    detectTime: '2025-10-05',
    isOverdue: '已超期',
    status: '停用',
    industryUnit: '柯城区交通运输局',
    industryPerson: '毕华',
    industryContact: '0570-3030001',
    facilityManageUnit: '柯城区市政管理处',
    facilityManagePerson: '颜青',
    facilityManageContact: '0570-3030002',
    facilityMaintainUnit: '柯城区公路养护段',
    facilityMaintainPerson: '霍亮',
    facilityMaintainContact: '0570-3030003',
    policeUnit: '柯城区交警大队',
    policeContact: '阮超',
    policeContactPhone: '0570-3030004',
    roadLocation: '柯城区府东街衢江路至荷花路段',
    detectRecords: [
      { id: 1, name: '定期检测', checkTime: '2025-10-05', type: '定期检测', evalGrade: 'D', result: '已整改销号' },
      { id: 2, name: '经常检查', checkTime: '2025-10-01', type: '经常检查', evalGrade: 'D', result: '' },
    ],

  },
  {
    key: '16',
    region: '舟山市定海区',
    name: '昌洲大道（文化路-东皋路）改建工程',
    level: '主干路',
    buildTime: '2018-03-14',
    hasMonitorDevice: true,
    hasMonitorFacility: true,
    evalLevel: 'A',
    evalYear: 2025,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-07-18',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '定海区交通运输局',
    industryPerson: '于海',
    industryContact: '0580-2020001',
    facilityManageUnit: '定海区市政设施管理中心',
    facilityManagePerson: '安琪',
    facilityManageContact: '0580-2020002',
    facilityMaintainUnit: '定海区道路养护公司',
    facilityMaintainPerson: '马骏',
    facilityMaintainContact: '0580-2020003',
    policeUnit: '定海区交警大队',
    policeContact: '乐威',
    policeContactPhone: '0580-2020004',
    roadLocation: '定海区昌洲大道文化路至东皋路段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-07-18', type: '常规检测', evalGrade: 'A', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-07-01', type: '经常检查', evalGrade: 'A', result: '' },
    ],

  },
  {
    key: '17',
    region: '嘉兴市南湖区',
    name: '中环南路（城南路-纺工路）整治工程',
    level: '次干路',
    buildTime: '2020-08-22',
    hasMonitorDevice: true,
    hasMonitorFacility: false,
    evalLevel: 'B',
    evalYear: 2024,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-04-30',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '南湖区交通运输局',
    industryPerson: '程辉',
    industryContact: '0573-8280001',
    facilityManageUnit: '南湖区市政设施管理所',
    facilityManagePerson: '丁宁',
    facilityManageContact: '0573-8280002',
    facilityMaintainUnit: '南湖区道路养护中心',
    facilityMaintainPerson: '魏兵',
    facilityMaintainContact: '0573-8280003',
    policeUnit: '南湖区交警大队',
    policeContact: '任远',
    policeContactPhone: '0573-8280004',
    roadLocation: '南湖区中环南路城南路至纺工路段',
    detectRecords: [
      { id: 1, name: '常规检测', checkTime: '2026-04-30', type: '常规检测', evalGrade: 'B', result: '' },
      { id: 2, name: '经常检查', checkTime: '2026-04-01', type: '经常检查', evalGrade: 'B', result: '' },
    ],

  },
  {
    key: '18',
    region: '湖州市安吉县',
    name: '递铺路（天荒坪路-玉华路）改造工程',
    level: '支路',
    buildTime: '2017-11-30',
    hasMonitorDevice: false,
    hasMonitorFacility: false,
    evalLevel: 'C',
    evalYear: 2023,
    dataComplete: true,
    publishStatus: '已发布',
    detectTime: '2026-01-20',
    isOverdue: '未超期',
    status: '在用',
    industryUnit: '安吉县交通运输局',
    industryPerson: '华强',
    industryContact: '0572-5030001',
    facilityManageUnit: '安吉县市政管理处',
    facilityManagePerson: '方圆',
    facilityManageContact: '0572-5030002',
    facilityMaintainUnit: '安吉县公路养护段',
    facilityMaintainPerson: '董明',
    facilityMaintainContact: '0572-5030003',
    policeUnit: '安吉县交警大队',
    policeContact: '贾磊',
    policeContactPhone: '0572-5030004',
    roadLocation: '安吉县递铺路天荒坪路至玉华路段',
    detectRecords: [
      { id: 1, name: '定期检测', checkTime: '2026-01-20', type: '定期检测', evalGrade: 'C', result: '已整改销号' },
      { id: 2, name: '经常检查', checkTime: '2026-01-01', type: '经常检查', evalGrade: 'C', result: '' },
    ],

  },
]

// 模拟获取道路列表
export function getRoadList(
  params: RoadSearchParams
): Promise<{ list: RoadItem[]; total: number; page: number; pageSize: number }> {
  return new Promise((resolve) => {
    setTimeout(() => {
      let filteredList = [...mockRoads]

      // 筛选
      if (params.region) {
        filteredList = filteredList.filter((item) => item.region.includes(params.region!))
      }
      if (params.name) {
        filteredList = filteredList.filter((item) => item.name.includes(params.name!))
      }
      if (params.level) {
        filteredList = filteredList.filter((item) => item.level === params.level)
      }
      if (params.evalLevel) {
        filteredList = filteredList.filter((item) => item.evalLevel === params.evalLevel)
      }
      if (params.status) {
        filteredList = filteredList.filter((item) => item.status === params.status)
      }
      if (params.dataComplete) {
        const val = params.dataComplete === '是'
        filteredList = filteredList.filter((item) => item.dataComplete === val)
      }
      if (params.publishStatus) {
        filteredList = filteredList.filter((item) => item.publishStatus === params.publishStatus)
      }
      if (params.isOverdue) {
        filteredList = filteredList.filter((item) => item.isOverdue === params.isOverdue)
      }

      // 分页
      const total = filteredList.length
      const page = params.page || 1
      const pageSize = params.pageSize || 10
      const start = (page - 1) * pageSize
      const end = start + pageSize
      const list = filteredList.slice(start, end)

      resolve({
        list,
        total,
        page,
        pageSize,
      })
    }, 500)
  })
}

// 归属地区选项 — 浙江省11个地市的区县
export const regionOptions = [
  { label: '杭州市市辖区', value: '杭州市市辖区' },
  { label: '杭州市余杭区', value: '杭州市余杭区' },
  { label: '杭州市拱墅区', value: '杭州市拱墅区' },
  { label: '杭州市西湖区', value: '杭州市西湖区' },
  { label: '杭州市滨江区', value: '杭州市滨江区' },
  { label: '杭州市萧山区', value: '杭州市萧山区' },
  { label: '宁波市市辖区', value: '宁波市市辖区' },
  { label: '宁波市镇海区', value: '宁波市镇海区' },
  { label: '温州市平阳县', value: '温州市平阳县' },
  { label: '嘉兴市南湖区', value: '嘉兴市南湖区' },
  { label: '嘉兴市嘉兴港区', value: '嘉兴市嘉兴港区' },
  { label: '湖州市南太湖新区', value: '湖州市南太湖新区' },
  { label: '湖州市安吉县', value: '湖州市安吉县' },
  { label: '绍兴市柯桥区', value: '绍兴市柯桥区' },
  { label: '金华市兰溪市', value: '金华市兰溪市' },
  { label: '金华市义乌市', value: '金华市义乌市' },
  { label: '丽水市缙云县', value: '丽水市缙云县' },
  { label: '台州市椒江区', value: '台州市椒江区' },
  { label: '衢州市柯城区', value: '衢州市柯城区' },
  { label: '舟山市定海区', value: '舟山市定海区' },
]

// 道路等级选项 — 线上系统用词
export const roadLevelOptions = [
  { label: '快速路', value: '快速路' },
  { label: '主干路', value: '主干路' },
  { label: '次干路', value: '次干路' },
  { label: '支路', value: '支路' },
]

// 综合评价等级选项
export const evalLevelOptions = [
  { label: 'A', value: 'A' },
  { label: 'B', value: 'B' },
  { label: 'C', value: 'C' },
  { label: 'D', value: 'D' },
  { label: 'E', value: 'E' },
]

// 发布状态选项
export const publishStatusOptions = [
  { label: '草稿', value: '草稿' },
  { label: '已发布', value: '已发布' },
]

// 检测是否超期选项
export const isOverdueOptions = [
  { label: '未超期', value: '未超期' },
  { label: '已超期', value: '已超期' },
]

// 数据是否完善选项
export const dataCompleteOptions = [
  { label: '是', value: '是' },
  { label: '否', value: '否' },
]

// 状态选项
export const statusOptions = [
  { label: '在用', value: '在用' },
  { label: '在建', value: '在建' },
  { label: '停用', value: '停用' },
]
